### ISSUE TITLE
Carousel / Gallery

### ISSUE THREAD

**Issue by fzembow** [phosphor-icons/homepage#100]
**Describe the requested icon**

My specific use case is a UI toggle split button for changing between different views of an image gallery. One of my modes is a "filmstrip", which you already have, but there isn't a good "gallery" treatment that I was able to find.

**Screenshots**

One idea would be a combination of the caret-left and caret-right icons already existing with an image, something skin to:

![image](https://user-images.githubusercontent.com/497031/151891625-ea451d5c-dbb8-4c28-8bff-5565217d29f5.png)

This is what I went with, implemented using Tailwind

```tsx
const Carousel: FC = () => (
  <div className="flex items-center">
    <CaretLeft size={10} className="-mr-1" />
    <ImageSquare />
    <CaretRight size={10} className="-ml-1" />
  </div>
);
```

An alternative approach would be to do something similar to the iOS Finder icon for its gallery view:

![image](https://user-images.githubusercontent.com/497031/151891715-63a24001-a75d-487b-8da5-0c4f6752fb52.png)

**Additional context**

I love phosphor icons, thank you in particular for having really clean SVG markup :)

**Comment by rektdeckard** [comment]
Added `slideshow` in v2.0.0
