### ISSUE TITLE
Icon Request: WeChat / Weixin

### ISSUE THREAD

**Issue by hzlzh** [phosphor-icons/homepage#101]
WeChat is the NO.1 chat App here in Chinese like message and facebook, please can you add icon for that.

https://wechat.design/standard/brand/main-brand#%E5%BE%AE%E4%BF%A1%E6%A0%87%E5%BF%97

<img width="700" alt="image" src="https://user-images.githubusercontent.com/1049575/153215240-0dd1079b-e5bc-4d09-99af-1b129e02b2ba.png">

<img width="1039" alt="image" src="https://user-images.githubusercontent.com/1049575/153214976-0da1567b-5039-4674-bb7e-f578e12c7ad5.png">

**Comment by rektdeckard** [comment]
Added `wechat-logo` in v2.0.0
