### ISSUE TITLE
Tooth

### ISSUE THREAD

**Issue by vladstudio** [phosphor-icons/homepage#104]
**Describe the requested icon**
Sounds really weird, but I need a tooth icon, and I do not want to give up on Phosphor set just because it has no tooth!

**Additional context**
I'm attaching my modest attempt to design a tooth icon in Phosphor style.

![tooth](https://user-images.githubusercontent.com/914320/154813866-b6f38384-0cd4-491e-acaa-d1aef607d480.svg)

**Comment by rektdeckard** [comment]
Not weird! Or if it is, weird is good. 🦷  Added `tooth` in v2.0.0
