### ISSUE TITLE
Icon request: Goodreads

### ISSUE THREAD

**Issue by moonflowcr** [phosphor-icons/homepage#107]
**Describe the requested icon**
A Goodreads icon added to your brands category to link to my profile without having to use other icon fonts for it. I think Phosphoricons deserves to have one!

**Screenshots**
![image](https://user-images.githubusercontent.com/100689866/156163639-47126d05-c80c-431d-925c-777a063fcc29.png)
![image](https://user-images.githubusercontent.com/100689866/156163670-38accb24-80ff-4af9-b96d-3b274471217b.png)

**Comment by rektdeckard** [comment]
Added `goodreads-logo` in v2.0.0
