### ISSUE TITLE
Meta logo

### ISSUE THREAD

**Issue by ThatGrimshaw** [phosphor-icons/homepage#108]
**Describe the requested icon**
The Meta logo, probably without the wordmark (I think the existing Facebook logo should stay too)

**Screenshots**
![image](https://user-images.githubusercontent.com/31192190/156221458-d1544cb7-ae91-4444-a003-702b564c6731.png)
![image](https://user-images.githubusercontent.com/31192190/156221520-1b333714-2bbf-4f63-b6c4-2f44dc691a5a.png)

**Comment by rektdeckard** [comment]
Added `meta-logo` in v2.0.0
