### ISSUE TITLE
Different character icons

### ISSUE THREAD

**Issue by Stefan-Hybschmann** [phosphor-icons/homepage#110]
**Describe the requested icon**
Explain the icon you'd like to see, and potential use-cases.
Would love to have an icon with a user in:
- formal attire (jacket and tie).
- cowboy hat

**Comment by rektdeckard** [comment]
Added `shirt-folded`, `high-heel`, and some other clothing items in v2.0.0. `cowboy-hat` and `suit-and-tie` are in our backlog 👍 What other kinds of characters did you have in mind?
