### ISSUE TITLE
healthcare and human internal organs icon

### ISSUE THREAD

**Issue by medibuddy-bright** [phosphor-icons/homepage#114]
It would be nice if icons that could be used in hospitals, pharmacies, or healthcare fields such as healthcare and human internal organs were added!

It would be nice if it could be used to express a disease or the department of a hospital.

thank you!
(This article was written with Google Translate, so it may be awkward.)

**Comment by rektdeckard** [comment]
Thanks for the request! Added `bone`, `tooth`, `stethoscope`, `dna`, `virus`  in v2.0.0

**Comment by rektdeckard** [comment]
We also already have `pill`, `prescription`, `brain`, `face-mask`, `heart`, `heartbeat`, `syringe`, and a number of first-aid icons.
