### ISSUE TITLE
Different GitHub logo icon

### ISSUE THREAD

**Issue by crownedfoxes** [phosphor-icons/homepage#116]
**Describe the requested icon**
This might just be me, but the current GitHub icon looks a little weird, and may not be as recognisable as the actual logo. I'm requesting an icon that looks a little more like the official logo.

**Screenshots**
![github-mark-logo-400x400](https://user-images.githubusercontent.com/18042873/159143347-d0f93e40-5830-4196-98f4-a4f23d1de5d4.png)
![external-content duckduckgo com](https://user-images.githubusercontent.com/18042873/159143372-b0e9f5aa-72a5-49ea-87e2-c131fdee9318.jpg)

**Comment by rektdeckard** [comment]
Revised `github-logo` to look more like their actual logo in v2.0.0!
