### ISSUE TITLE
Code block icon

### ISSUE THREAD

**Issue by dasveloper** [phosphor-icons/homepage#117]
**Describe the requested icon**
Rich text editors often need to specify the difference between `inline code` and 
```
blocks of code
```

It would be nice to have a new icon to represent code block better. The standard is typically a little box with the code brackets in the corner.

**Screenshots**
<img width="785" alt="Screen Shot 2022-03-21 at 9 20 05 AM" src="https://user-images.githubusercontent.com/28981975/159270091-c3967931-ee2f-4c26-b84e-cf88ac15d676.png">
<img width="728" alt="Screen Shot 2022-03-21 at 9 19 21 AM" src="https://user-images.githubusercontent.com/28981975/159270086-57ed9721-d2d5-4794-83a5-39864cc33d11.png">

**Comment by rektdeckard** [comment]
Added `code-block` in v2.0.0
