### ISSUE TITLE
Icon Request: Toolbox

### ISSUE THREAD

**Issue by aNerdyNotioneer** [phosphor-icons/homepage#119]
**Describe the requested icon**
Explain the icon you'd like to see, and potential use-cases.

I would like to see a toolbox icon. As a Notion user, I would use this icon for a maintenance/backend page. 

**Screenshots**
If applicable, add screenshots to help illustrate the icon appearance.

No screenshots. Not picky here. There are many variants that could be used. 
One could be just the toolbox itself. Another could be just a wrench and screwdriver crossing each other, etc. 

**Additional context**
Add any other context here.

I love your icons! I use them quite a bit for my Notion pages! Can't wait to see more.

**Comment by rektdeckard** [comment]
Added `toolbox`, `hammer` in v2.0.0
