### ISSUE TITLE
Icon refinement: filled Leaf (the stalk looks off)

### ISSUE THREAD

**Issue by adroste** [phosphor-icons/homepage#123]
**Describe the requested icon**

I want to use the leaf icon (preferably filled) in a context where it should be associated with sustainability.
I think that especially in the *filled* version the leaf stalk can be hardly recognized.

Ideas: 
1. Extend the leaf stalk
2. Offset the leaf stalk ( like in fa https://fontawesome.com/icons/leaf?s=solid )

**Screenshots**

![Screen Shot 2022-04-09 at 19 33 41](https://user-images.githubusercontent.com/18649298/162585092-e7472203-5ca2-45e0-9cb4-c8fcd8a80604.png)

**Comment by rektdeckard** [comment]
Slightly revised `leaf` per your suggestion, and added `plant`, `potted-plant` in v2.0.0
