### ISSUE TITLE
Correct use with pixel snapping at 24px size

### ISSUE THREAD

**Issue by dpschen** [phosphor-icons/homepage#127]
**Describe the bug**
Icons not snapping pixel grid at 24px size

**Expected behavior**
Icons snapping grid.

**Screenshots**
![image](https://user-images.githubusercontent.com/6173598/165727085-7ede1027-9c72-4e4b-94b2-633318c8900d.png)

**Additional context**
I found this related issue but it doesn't answer my usecase: https://github.com/phosphor-icons/phosphor-home/issues/26

**Comment by rektdeckard** [comment]
Hey @dpschen! The recent 2.0 release improves pixel-fitting for a huge number of icons, but perfect snapping is not part of our mission statement, and isn't really possible for a variable-sized icon set. That said, we expect you'll see some improvements using the latest release.
