### ISSUE TITLE
Airport control tower

### ISSUE THREAD

**Issue by ruymon** [phosphor-icons/homepage#131]
**Icon description**
The representation of an airport control tower is similar to an antenna but a building.

**Screenshots**
Real Control Tower inspirations:
![image](https://user-images.githubusercontent.com/50504050/167281975-e6602f53-1bc5-4b8e-a56f-0d1564ac0345.png)
![image](https://user-images.githubusercontent.com/50504050/167282071-daa866ed-6ab6-42f6-9a4a-98cef8d80bfa.png)
![image](https://user-images.githubusercontent.com/50504050/167282076-eb0dd0a0-43c9-4068-825d-ff0a37112b94.png)

Example icon from other packs:
![image](https://user-images.githubusercontent.com/50504050/167282023-63403929-31ca-4a04-929e-2f8684b5c92e.png)
![image](https://user-images.githubusercontent.com/50504050/167282062-f4cc8ca7-3ebf-4337-a210-9ef27c5ff050.png)

**Additional context**
N/A

**Comment by rektdeckard** [comment]
Added `air-traffic-control` in v2.0.0
