### ISSUE TITLE
Pig Icon

### ISSUE THREAD

**Issue by gustavo-flor** [phosphor-icons/homepage#132]
A simple pig icon, it can be used in any context that relates, for example my team want to use like a Money Vault in a financial app.

Something like this:
<img width="188" alt="Screen Shot 2022-05-09 at 15 44 49" src="https://user-images.githubusercontent.com/39883705/167476521-249000b9-a0d6-45d2-a686-b7b43ff0054c.png">

**Comment by AmruthPillai** [comment]
I would also like this kind of icon, to denote a piggy bank, savings, budget section of an app I'm currently building. I can't think of any other icons to use as a workaround for this, so open to suggestions :)

**Comment by rektdeckard** [comment]
Added `piggy-bank` in v2.0.0
