### ISSUE TITLE
Clothing

### ISSUE THREAD

**Issue by ludiusdev** [phosphor-icons/homepage#136]
There is a lack of clothing items, examples of clothing items that can be added are: shoes, bags, hoodies, t-shirts, etc.
These could be used in clothing stores to describe categories without using words.

**Comment by rektdeckard** [comment]
Added `baseball-cap`, `boot`, `sneaker`, `sneaker-move`, `high-heel`, `dress`, `hoodie`, `pants`, `shirt-folded` in v2.0.0

**Comment by rektdeckard** [comment]
`t-shirt`, `coat-hanger` are already present in the library 👍
