### ISSUE TITLE
Motorcycle icon

### ISSUE THREAD

**Issue by andres-reyes-r** [phosphor-icons/homepage#137]
A motorcylce to complete the transport methods collection. It would be helpful for shipping/delivery cases

**Screenshots**
![image](https://user-images.githubusercontent.com/61883422/169915221-86e8a48b-fd17-43c3-8b69-d626ea6dcb49.png)

![image](https://user-images.githubusercontent.com/61883422/169915306-2fb6b757-33f5-46ad-90c5-0ea0a0d7b5cf.png)
![image](https://user-images.githubusercontent.com/61883422/169915447-e22e4dd0-31ae-40be-b00a-f6e2aa6f7b03.png)

**Comment by rektdeckard** [comment]
Added `motorcycle`, `moped`, `moped-front`, `scooter` in v2.0.0

**Comment by andres-reyes-r** [comment]
Thanks, Tobias, it looks awesome :3
