### ISSUE TITLE
Prayer Hand Icon

### ISSUE THREAD

**Issue by ivanchaukn** [phosphor-icons/homepage#138]
**Describe the requested icon**
Hand in the praying position. Potentially just remove the streaks on the clapping hand

**Comment by ivanchaukn** [comment]
![Prayer V2](https://user-images.githubusercontent.com/8071296/180354436-6f429202-5409-418e-89a5-baaf550b673c.svg)
Here an icon that we think will fit in the icon set. @rektdeckard  Please let me know your thoughts and I can get my design to generate the other variation if you are good with this icon

**Comment by rektdeckard** [comment]
Added `hands-praying` in v2.0.0
