### ISSUE TITLE
Error/Critical icon

### ISSUE THREAD

**Issue by megaroeny** [phosphor-icons/homepage#141]
**Describe the requested icon**
You currently have a warning icon, would be nice to provide another icon that represents something more "critical" than warning (like for an error.)

With `warning` having the triangle outline, `critical` or `error` could have a diamond shape (rotated square.) This will provide a clearer distinction compared to `warning-octagon`.

**Screenshots**
Here is an example of an `alert` component in the "error" state, that provides various types:
![image](https://user-images.githubusercontent.com/1559447/172242291-a42689d7-ffac-474a-871f-e16bc464bae1.png)

**Additional context**
This can provide a full range of alerts/statuses: info, success, warning, error/critical. This will also be an Accessibility improvement because you can't always rely on color to communicate these things.

**Comment by rektdeckard** [comment]
Added `warning-diamond`, `warning-cloud` in v2.0.0
