### ISSUE TITLE
More vehicle icons :)

### ISSUE THREAD

**Issue by srodd89** [phosphor-icons/homepage#145]
Hey, 

It would be great if there were a few more types of vehicle icons such as - 

Scooter
Moped 
Cargo bike
Van 

Thank you!

**Comment by rektdeckard** [comment]
Added `motorcycle`, `moped`, `moped-front`, `scooter`, `car-profile`, `van`, `steering-wheel` `engine`, `tram`, `garage` in v2.0.0
