### ISSUE TITLE
 Brazilian payment method icon PIX

### ISSUE THREAD

**Issue by pierrefrota** [phosphor-icons/homepage#146]
**Describe the requested icon**
It will be used to represent a payment method widely used in Brazil

**Comment by klawdyo** [comment]
SVG source:
https://pt.wikipedia.org/wiki/Ficheiro:Logo%E2%80%94pix_powered_by_Banco_Central_(Brazil,_2020).svg

**Comment by fabriciop-carvalho** [comment]
I was in need of the same icon, and I noticed that they have one very similar to the Pix icon called `diamonds-four`
cc: @pierrefrota 

<img width="555" alt="image" src="https://github.com/phosphor-icons/homepage/assets/78507414/d82736fe-3b02-4fde-9580-d21e29e97cb5">
