### ISSUE TITLE
Building / Office annotation icons

### ISSUE THREAD

**Issue by stangrootes** [phosphor-icons/homepage#147]
I would love to have some building / office annotation icons in the phosphor icon set. For example: toilet, elevator, stairs, lockers and reception.

**Comment by stangrootes** [comment]
I would also love a desk and a meeting room icon :)

**Comment by rektdeckard** [comment]
Added `elevator`, `escalator-down`, `escalator-up`, `stars`, `steps`, `lockers`, `door-open`, `call-bell` in v2.0.0, and `buildings`, `doors`, `toilet` and `toilet-paper` have been around since previous releases. Hope this is what you need!

**Comment by rektdeckard** [comment]
`desk` is in our backlog.
