### ISSUE TITLE
Swimming Pool

### ISSUE THREAD

**Issue by juninholiveira** [phosphor-icons/homepage#149]
**Describe the requested icon**
Icons representing a swimming pool could be useful for a lot of situations, for example, to represent amenities in a hotel. There could be multiple icons representing waves

**Screenshots**
Some screenshot examples taken showing some Swimmig Pool icons for reference.
![image](https://user-images.githubusercontent.com/10757100/175821576-d35fd040-bf61-4458-8a03-a29be13da705.png)
![image](https://user-images.githubusercontent.com/10757100/175821587-eef94c12-749a-4abe-af37-cab6a8cf563d.png)
![image](https://user-images.githubusercontent.com/10757100/175821598-4512ec53-8f03-4f75-bd14-7e688d44afd8.png)
![image](https://user-images.githubusercontent.com/10757100/175821604-9e90ad17-d385-413c-b346-a83e7f1c9ae2.png)
![image](https://user-images.githubusercontent.com/10757100/175821612-30270627-ef33-40d8-8d2d-cb1ef862aba4.png)

**Comment by rektdeckard** [comment]
Added `swimming-pool` in v2.0.0
