### ISSUE TITLE
Park Icons

### ISSUE THREAD

**Issue by juninholiveira** [phosphor-icons/homepage#150]
**Describe the requested icon**
Icons for green parks on a city.

**Screenshots**
![image](https://user-images.githubusercontent.com/10757100/175821726-7e38d852-a77d-4117-878e-32aeaa4cd9ed.png)
![image](https://user-images.githubusercontent.com/10757100/175821734-97a2c8ec-00bd-461a-876c-d5217bd78ad7.png)
![image](https://user-images.githubusercontent.com/10757100/175821747-21509ccd-66c3-40a9-b57d-1f6560993146.png)

**Comment by rektdeckard** [comment]
Added `park` in v2.0.0
