### ISSUE TITLE
Webhook Icon

### ISSUE THREAD

**Issue by wladiston** [phosphor-icons/homepage#151]
**Describe the requested icon**
Maybe a low priority icon but I'd love to see more icons related to integrations like the webhook one

**Screenshots**
![image](https://user-images.githubusercontent.com/1843792/176242611-e0e3cd5e-d5c1-4ec1-8210-8fd5de377b73.png)
![image](https://user-images.githubusercontent.com/1843792/176242635-9efb5ba5-cf69-4c14-9369-09c7900d8983.png)

**Comment by rektdeckard** [comment]
Added `webhooks-logo` in v2.0.0
