### ISSUE TITLE
Speaker icon (hardware)

### ISSUE THREAD

**Issue by lolouthefox** [phosphor-icons/homepage#152]
**Describe the requested icon**
Pretty basic and helpful icon; the speaker icon. I'll need the hardware one, as shown in the picture bellow:
**Screenshots**
![speaker_FILL0_wght400_GRAD0_opsz48](https://user-images.githubusercontent.com/96738841/177034241-b99f35b6-9aca-4935-83a7-30bfc63a09ac.png)

**Additional context**
Thank you so much for these icons, they look so good ! This is the best icon pack I've found so far !

**Comment by rektdeckard** [comment]
Added `speaker-hifi` in v2.0.0
