### ISSUE TITLE
Phosphor icons in Unicode

### ISSUE THREAD

**Issue by moonflowcr** [phosphor-icons/homepage#154]
I have a question: will we be able to use Phosphor icons in Unicode to use them directly in CSS in the future? Let's say I want to add an icon before the text within a `<div>` using Unicode, will we have that option in the future like some other icon fonts like FontAwesome do?

**Comment by rektdeckard** [comment]
Our [@phosphor-icons/web](https://github.com/phosphor-icons/web) library is implemented as an icon font. Though we don't have a dictionary of Unicode code points for each icon (duotone weight actually uses 2 code points), you can inspect the [stylesheet](https://github.com/phosphor-icons/web/blob/master/src/regular/style.css) of one of the weights to see what glyphs map to what code points.

From there, it's a matter of using one of our fonts in your `<div>`, and printing the right unicode character.

Unfortunately we don't support font ligatures any more, but it's something we're hoping to bring back.
