### ISSUE TITLE
Textarea resize icon

### ISSUE THREAD

**Issue by DaveKeehl** [phosphor-icons/homepage#155]
**Describe the requested icon**
It might be useful to have a textarea resize icon, like the one that shows in native HTML textarea elements.

**Screenshots**
<img width="220" alt="Screen Shot 2022-07-12 at 18 09 28" src="https://user-images.githubusercontent.com/34663397/178541053-91d2dea9-073f-4f27-9a83-ec8e008256a2.png">

**Comment by rektdeckard** [comment]
Added `notches` in v2.0.0
