### ISSUE TITLE
Wrench icon in Figma plugin has path not closed

### ISSUE THREAD

**Issue by DaveKeehl** [phosphor-icons/homepage#158]
**Describe the bug**
I just noticed that in the Phosphor Icons Figma plugin the wrench icon has the path not closed. The icon preview inside the plugin looks fine, but when the icon is dragged in the canvas, then you can the see path not being closed.

**To Reproduce**
1. Go to Figma
2. Open the Phosphor Icons Figma plugin
3. Search for "wrench" (doesn't matter which weight variant, as long as it's not "fill")
4. Drag the icon in the canvas
5. See the path not being closed 

**Expected behavior**
There shouldn't be a small gap in the icon path

**Screenshots**
<img width="696" alt="Screen Shot 2022-07-16 at 09 35 17" src="https://user-images.githubusercontent.com/34663397/179345317-eaeaad4c-54b4-4866-a6ae-63983b43971b.png">

**Additional context**
Not sure if it matters, but I'm using the Figma desktop app.

**Comment by rektdeckard** [comment]
cc @minoraxis

**Comment by DaveKeehl** [comment]
Just noticed that the ChatCircle icon has the same issue.

<img width="793" alt="Screen Shot 2022-10-01 at 18 14 40" src="https://user-images.githubusercontent.com/34663397/193418450-48556c06-9ac3-4032-9e1d-e9be1cf07efa.png">

**Comment by minoraxis** [comment]
Thanks for reporting this! We'll take a look in the next release. It's a known issue when translating from Illustrator to Figma. I found that if you click the anchor point that looks broken, it should fix itself.

**Comment by DaveKeehl** [comment]
@minoraxis I see, I'll try to follow your suggestion! Any update on the next release?

**Comment by rektdeckard** [comment]
New release is live, with fixes for this bug 👍
