### ISSUE TITLE
Subtitle icon

### ISSUE THREAD

**Issue by bramhaag** [phosphor-icons/homepage#159]
**Describe the requested icon**
A subtitle icon is currently missing. While there is a closed captions icon, in most cases subtitles are not closed captions and therefore this icon is not applicable.

**Screenshots**
![image](https://user-images.githubusercontent.com/5541521/179379439-2d7aa8f5-749b-4cec-b374-06f67215ef65.png)

**Comment by rektdeckard** [comment]
Added `subtitles` in v2.0.0
