### ISSUE TITLE
Manage Search

### ISSUE THREAD

**Issue by riyadhg** [phosphor-icons/homepage#161]
**Describe the requested icon**
A manage search icon, when a user clicks on an icon like this they would ideally see a mega menu with search capability.

**Screenshots**
![Manage Search](https://user-images.githubusercontent.com/98850293/180182118-d80bb8f5-434e-43e6-af05-f53f1d38d00a.png)

**Additional context**
[Google Icon](https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Amanage_search%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4048)

**Comment by rektdeckard** [comment]
Added `list-magnifying-glass` in v2.0.0
