### ISSUE TITLE
Church Icon

### ISSUE THREAD

**Issue by cunhaedu** [phosphor-icons/homepage#162]
**Request description**
A Catedral icon would be very usefull, I'm needing one to a project for my church, specifically in the churchs locations menu

**Screenshots**
![image](https://user-images.githubusercontent.com/60043166/180619563-3c365414-57fa-44af-88e2-47beced802d6.png)

**Comment by rektdeckard** [comment]
Added `church`, `cross`, `mosque`, `star-and-crescent`, `synagogue`, `star-of-david`, `hands-praying`, `pentagram` in v2.0.0
