### ISSUE TITLE
Sports icons

### ISSUE THREAD

**Issue by boriskirov** [phosphor-icons/homepage#165]
**Describe the requested icon**
I'd like to use icons for sport activities like running, swimming, biking and tennis. I'd appreciate if there are two styles available:
- an individual doing the activity
- the main object from the sport (sports shoe, bike, swimming googles etc)

**Comment by rektdeckard** [comment]
Added `baseball-cap`, `goggles`, `boot`, `sneaker`, `sneaker-move`, `person-simple-bike`, `person-simple-throw` in v2.0.0. We'll be adding more people doing activities in future releases, please feel free to open up a new ticket with specific requests!
