### ISSUE TITLE
Chart Icons

### ISSUE THREAD

**Issue by crobbins215d** [phosphor-icons/homepage#166]
Describe the requested icon
Could further chart icons be added, for example, Doughnut Chart & Polar Chart

Example Chart Components
[Chart](https://react-chartjs-2.js.org/components/chart)
[Bar](https://react-chartjs-2.js.org/components/bar)
[Line](https://react-chartjs-2.js.org/components/line)
[Pie](https://react-chartjs-2.js.org/components/pie)
[Doughnut](https://react-chartjs-2.js.org/components/doughnut)
[PolarArea](https://react-chartjs-2.js.org/components/polar-area)
[Radar](https://react-chartjs-2.js.org/components/radar)
[Scatter](https://react-chartjs-2.js.org/components/scatter)
[Bubble](https://react-chartjs-2.js.org/components/bubble)

https://react-chartjs-2.js.org/examples

**Comment by rektdeckard** [comment]
Added `chart-donut`, `chart-polar`, `chart-scatter`, `chart-line-down` in v2.0.0
