### ISSUE TITLE
XING Icon

### ISSUE THREAD

**Issue by dominikgeimer** [phosphor-icons/homepage#168]
**Describe the requested icon**
XING is the biggest career portal in Germany.

**Screenshots**
![image](https://user-images.githubusercontent.com/6383607/184164137-130ac541-0367-4ab7-8f92-91109996e333.png)

**Additional context**
Love the icons! Thanks so much for your hard work!

**Comment by rektdeckard** [comment]
Hi @dominikgeimer, unfortunately things like this are a little too specific and out of scope for this project. In general, we recommend using official brand assets anyway. See #392 for more info.
