### ISSUE TITLE
Furniture

### ISSUE THREAD

**Issue by ijsthee** [phosphor-icons/homepage#17]
Requesting more furniture icons 

Things like a bath tub, shower, chair, sofa, door, lamp etc

<img width="301" alt="Screenshot 2020-12-18 at 12 14 13 PM" src="https://user-images.githubusercontent.com/76208792/102608727-a5bd2380-412a-11eb-9843-8a1332f9b33f.png">

**Comment by rektdeckard** [comment]
`lamp`, `door`, `armchair`  added in 1.2.0! We'll try to expand on this set for the following release :)

**Comment by minoraxis** [comment]
`shower` has been added in 1.3.1! More to come.

**Comment by minoraxis** [comment]
Added `bathtub` and `rug` in 1.4.

**Comment by rektdeckard** [comment]
Added `chair`, `couch`, `office-chair`, `stool`, `lockers`, `door-open` in v2.0.0. Hope this meets your needs! Anything else specific, feel free to file another issue!
