### ISSUE TITLE
Champagne Flute Icon

### ISSUE THREAD

**Issue by elise-lcdb** [phosphor-icons/homepage#172]
**Describe the requested icon**
A champagne flute icon to go with the martini glass

**Screenshots**
![CleanShot 2022-08-19 at 11 17 32](https://user-images.githubusercontent.com/31904512/185587412-b7ce0670-882d-4760-98b0-ce5d9c755cd1.png)

**Comment by rektdeckard** [comment]
Added `champagne` in v2.0.0
