### ISSUE TITLE
Doctor

### ISSUE THREAD

**Issue by sumitwagh** [phosphor-icons/homepage#173]
**Describe the requested icon**
Explain the icon you'd like to see, and potential use-cases.

**Screenshots**
If applicable, add screenshots to help illustrate the icon appearance.

**Additional context**
Add any other context here.

**Comment by rektdeckard** [comment]
Added `stethoscope`, `tooth`, `bone` in v2.0.0. We also have a number of medical-adjacent icons already. Hope this suits your needs.
