### ISSUE TITLE
Amazon Brand

### ISSUE THREAD

**Issue by emirchus** [phosphor-icons/homepage#177]
**Describe the requested icon**
Amazon, AWS and Amazon Prime logos, I would like to be able to use them with phosphor

**Screenshots**
![image](https://user-images.githubusercontent.com/32276305/188936294-49336938-ddb3-41fb-8d57-85bd5f6fb866.png)
![image](https://user-images.githubusercontent.com/32276305/188936342-d458def9-181a-436a-b580-669ad5f67952.png)
![image](https://user-images.githubusercontent.com/32276305/188936376-5cc1f953-f5ea-4e6c-8234-fb016980d101.png)

**Additional context**
I am creating my portfolio and need to use the logos of amazon, aws and prime video.

**Comment by rektdeckard** [comment]
Added `amazon-logo` in v2.0.0

**Comment by rektdeckard** [comment]
We may or may not get around to `aws` and `prime-video`, but they have been added to our backlog!
