### ISSUE TITLE
Read Only

### ISSUE THREAD

**Issue by tiffanynk** [phosphor-icons/homepage#178]
**Describe the requested icon**
An icon to indicate a file is "read-only" or not editable. A use case would be for an agreement that you don't need to sign but is informational.

**Screenshots**
A simple pencil with a slash or a document with an eye. 

Examples:
![pencil slash](https://user-images.githubusercontent.com/63679192/189995476-8ce8e4f6-9fda-41bf-9288-1d2c670c14c7.png)
![document eye](https://user-images.githubusercontent.com/63679192/189995530-b0d1855a-7e06-4c83-9e1d-5867845969c0.png)

**Comment by rektdeckard** [comment]
Added `pencil-slash` and `pencil-simple-slash` in v2.0.0
