### ISSUE TITLE
Patreon Logo

### ISSUE THREAD

**Issue by coelhucas** [phosphor-icons/homepage#179]
**Describe the requested icon**
As we already have other logo icons such as Linkedin, Twitter, Discord, etc, could be used to keep visual consistency and represent redirects to Patreon.

It is a very simple and already existing icon in other libraries, but having it here would be better than adding it individually :)

**Examples**
<img width="48" src="https://user-images.githubusercontent.com/28108272/192036748-432d123b-c5b0-45ba-8740-1b3bd042517f.png" />
<img width="48" src="https://user-images.githubusercontent.com/28108272/192036840-b986a0b3-c714-4ef9-bda4-c044eb154701.png" />

<img width="48" alt="image" src="https://user-images.githubusercontent.com/28108272/192036927-e7cf4c1d-ff0c-489a-a7fb-48c91f4458de.png">

[Patreon brand guidelines](https://www.patreon.com/brand)

**Comment by rektdeckard** [comment]
Added `patreon-logo` in v2.0.0
