### ISSUE TITLE
Usb icon

### ISSUE THREAD

**Issue by Quangdm-cdm** [phosphor-icons/homepage#186]
**Describe the requested icon**
I need to use the USB icon for my project, like in Fontawsome.

**Screenshots**
SVG link: 
![usb](https://user-images.githubusercontent.com/85857151/199385881-457873e5-f13e-428f-828c-d035120c9751.svg)

Screenshoot: 
![image](https://user-images.githubusercontent.com/85857151/199386081-8995cb0a-547f-4baa-a0fa-7f950283fbf1.png)

**Additional context**
Please help me, i really really need it

**Comment by rektdeckard** [comment]
Added `usb` in v2.0.0
