### ISSUE TITLE
Contactless

### ISSUE THREAD

**Issue by sreynoso** [phosphor-icons/homepage#188]
**Describe the requested icon**
“Contactless payment” refers to a no-touch form of payment using a credit, debit or gift card on a point-of-sale system equipped with the adequate technology. Its useful to fintech apps, e-commerce and shopping carts.

**Screenshots**
<img width="721" alt="image" src="https://user-images.githubusercontent.com/2766445/200676466-fd20f217-fb32-4e4b-8cf9-e8c99eb2d7ee.png">

**Additional context**
Add any other context here.

**Comment by rektdeckard** [comment]
Added `contactless-payment` in v2.0.0
