### ISSUE TITLE
Admin icon

### ISSUE THREAD

**Issue by BrittosMonteiro** [phosphor-icons/homepage#190]
**Description**
Icon that could translate the admin role into a symbol.

**Additional context**
I'm developing a platform in which I have a list of users, so that I wish I could display user's role with a symbol both for "common" user and admin user.

**Comment by rektdeckard** [comment]
We have icons like `user-gear`, `identification-card`, `identification-badge` that could convey this concept. Do you have other ideas, or an example for something specific you'd like to see?
