### ISSUE TITLE
Clean Energy & Construction Icons

### ISSUE THREAD

**Issue by kaminiiyer** [phosphor-icons/homepage#191]
It would be great to add a set of construction and clean energy technologies - would really help clean tech companies (like the one I work for) out. Examples include: construction hat, construction crane, permits, solar panels, EV chargers, heat pumps, solar panel on buildings, carports

**Comment by rektdeckard** [comment]
Added `charging-station` (EV charger) in v2.0.0. Would like to get to more of these in later releases!

**Comment by kaminiiyer** [comment]
thank you! if there is one icon I could vote for to prioritize, would love to see a solar panel icon next

**Comment by rektdeckard** [comment]
Added `solar-panel`, `solar-roof`, `crane`, crane-tower`, `blueprint`, `hard-hat`, `nuclear-plant`, `windmill` in [v2.0.1](https://github.com/phosphor-icons/homepage/releases/tag/v2.1.0)
