### ISSUE TITLE
Cleaning icon

### ISSUE THREAD

**Issue by pmpinto** [phosphor-icons/homepage#192]
**Describe the requested icon**
An icon that would resemble cleaning service.

**Screenshots**
![Screenshot 2022-11-25 at 11 41 52](https://user-images.githubusercontent.com/4265830/203978657-ef0ab483-7caf-4f53-8db6-8790b38e2fb7.png)
![Screenshot 2022-11-25 at 11 41 56](https://user-images.githubusercontent.com/4265830/203978658-3012eb99-1145-4a89-97ea-561b409e87bb.png)
(From Material Symbols)

**Comment by rektdeckard** [comment]
Added `broom` in v2.0.0

**Comment by pmpinto** [comment]
Lovely! Thanks a lot!
