### ISSUE TITLE
Plus Square and Minus Square

### ISSUE THREAD

**Issue by elise-lcdb** [phosphor-icons/homepage#193]
**Describe the requested icon**
Similar to the circles but have a version for the plus square and the minus square
**Screenshots**
Example of how it would look
![CleanShot 2022-11-28 at 14 16 31](https://user-images.githubusercontent.com/31904512/204287075-3af40b49-6f65-4eba-a1be-213e6d88f77d.png)

**Comment by rektdeckard** [comment]
Added `plus-square` and `minus-square` in v2.0.0
