### ISSUE TITLE
phosphoricons.com offline

### ISSUE THREAD

**Issue by scott-gr** [phosphor-icons/homepage#194]
[https://phosphoricons.com](https://phosphoricons.com)

Other than creating a local directory, is there another place to search/browse the icons?

**Comment by rektdeckard** [comment]
Our hosting service is in the middle of an outage: https://www.dreamhoststatus.com/

All raw SVG assets can always be found at https://github.com/phosphor-icons/phosphor-icons/tree/master/assets if you need to find anything immediately.

**Comment by rektdeckard** [comment]
Our icon library is also mirrored on various aggregators, like [Iconfinder](https://www.iconfinder.com/search/icons?family=phosphor-regular).

**Comment by rektdeckard** [comment]
And of course, if you need the real site for any reason, [archive.org](https://web.archive.org/web/20221126214214/https://phosphoricons.com/) from 2 days ago.
