### ISSUE TITLE
SQL icon

### ISSUE THREAD

**Issue by SorenHolstHansen** [phosphor-icons/homepage#195]
**Describe the requested icon**
We would like a SQL file icon, since we are making a folder tree and would like to give the .sql files a nice icon

**Screenshots**
The icon should preferably look like this (From flat icon), but if you would rather do it the way you have made your other file icons, that is fine too
![29594](https://user-images.githubusercontent.com/54755687/205048892-8f1246ac-dac7-47a4-b3ed-3e0ac2b2f69c.png)

**Comment by rektdeckard** [comment]
Added `file-sql` in v2.0.0
