### ISSUE TITLE
Paragraph mark / Pilcrow 

### ISSUE THREAD

**Issue by umgustavo** [phosphor-icons/homepage#197]
**Describe the requested icon**
A paragraph mark (also known as pilcrow sign), will be useful for text editors.

**Screenshots**
¶

![image](https://user-images.githubusercontent.com/19615514/205447094-fa662cbe-26cb-4616-a156-f26f1176468f.png)

**Comment by rektdeckard** [comment]
Added `paragraph` (pilcrow icon) in v2.0.0
