### ISSUE TITLE
Request: Improved accessibility

### ISSUE THREAD

**Issue by megaroeny** [phosphor-icons/homepage#201]
My company is doing a lot of work to improve our accessibility. I was wondering if there's a way you can improve the a11y of screen readers for your icons. Would that be something added to the SVG code? My knowledge here is limited. What would be the equivalent of `alt` text on images?

Thanks for the consideration

**Comment by rektdeckard** [comment]
We provide a means of adding arbitrary attributes to the icons in most of our framework libraries -- including the `aria-label` attribute, which seems to be an appropriate way to label an SVG. We won't add labels to the raw assets by default, as we feel that is up to the consumer of the icons to decide!

If you add some info about how you're using the icon set, I might be able to point you in the right direction.

**Comment by megaroeny** [comment]
Ah yes you're probably right. Thank you!
