### ISSUE TITLE
Discovery Icons

### ISSUE THREAD

**Issue by franparrastome** [phosphor-icons/homepage#203]
**Describe the requested icon**
Discovery is one of the most important actions that the human being can execute, from the kinder garden to any type of work, we are discovering new actions, activities, requirements, and so on.  If we can have an icon where we can highlight a discovery action would be wonderful. Could be lens, brains, compasses, or any element that could help to any discovery phase.

**Comment by rektdeckard** [comment]
We have icons like `brain`, `magnifying-glass`, `binoculars`, `compass` already. Do you have something specific in mind that's not in that list?
