### ISSUE TITLE
Auction Icon

### ISSUE THREAD

**Issue by Nachomuchacho** [phosphor-icons/homepage#205]
Hello, I would love to have an "auction" icon.

Here is an example:
<img width="229" alt="Screen Shot 2022-12-27 at 12 04 10" src="https://user-images.githubusercontent.com/121491591/209657531-5b2f37ba-ec62-41ee-87f2-fa09dafbbeec.png">

Thank you

**Comment by rektdeckard** [comment]
Added `gavel` in v2.0.0
