### ISSUE TITLE
[Question] About Future and Further Developments

### ISSUE THREAD

**Issue by dukesx** [phosphor-icons/homepage#212]
Hi, 

First of all, i would like to thank you guys for such an awesome piece of art. Fantastic work on the icons. Love them. I was looking around when i saw that the last release was in 2021, which seems pretty old. Are there any further developments planned for the icon library or has the development been stalled ?

**Comment by rektdeckard** [comment]
We have a major release planned for some time in the next few weeks, which will have some minor changes specifically to this package...including splitting the icon fonts up by weight, and shipping them in woff2 along with the existing formats. So you should see some size and perf improvements for minimal upgrade effort.

What specifically are you looking for in terms of improvements?

**Comment by rektdeckard** [comment]
Thanks so much for the feedback!

We have zero runtime dependencies and a very simple design, so we have zero vulnerabilities to patch. Other than that, it's just bugs and improvements. Don't be surprised if our updates are few and far-between, but rest assured the project is alive and well.

As a totally free (always and forever) side project, we haven't felt the need for a roadmap in the past -- we don't like to promise icons or features, and generally are not beholden to honor requests in any order, or at all. That being said, we plan on including support for React Server Components in the next release, along with some QoL changes in the Vue library. These things seem important to the community to know about, so we'll consider posting it up somewhere for all to see.

**Comment by dukesx** [comment]
Thank you and God bless.

Looking forward to many more years of Journey with Phosphor Icons.
