### ISSUE TITLE
CodepenLogo icon is not exported from  'phosphor-react'

### ISSUE THREAD

**Issue by Dpessheva** [phosphor-icons/homepage#213]
**Describe the bug**
There is an icon for Codepen logo but when imported gives an error that  CodepenLogo is not exported.

**Comment by rektdeckard** [comment]
I just verified it is exported and working as expected in `1.4.1`, and if the icon is present on our website, it is working as expected in the React package, since we use it there.

Can you share some more information? What version are you on? How are you consuming the package? What bundler?

**Comment by Dpessheva** [comment]
Hi, version "phosphor-react": "^1.3.1",
I am using it in a react component 
![import_icon](https://user-images.githubusercontent.com/31918715/216379348-b35970ea-66a1-497a-8625-aedb52cb0d8f.PNG)


![error](https://user-images.githubusercontent.com/31918715/216379419-21bd7225-c9d0-4dac-969d-0940d7a195ab.PNG)


![Icon_component](https://user-images.githubusercontent.com/31918715/216379969-eb84ace9-fcc3-4889-9740-38671f30a40a.PNG)


Will try 1.4.1 version

**Comment by Dpessheva** [comment]
it works as you said in 1.4.1

**Comment by rektdeckard** [comment]
Yep, this icon was not part of the library yet in `1.3.x`.

**Comment by rektdeckard** [comment]
I'll include the release version on the website, if it's helpful in the future!

**Comment by rektdeckard** [comment]
Version info is now included for each icon on the site:
<img width="218" alt="image" src="https://user-images.githubusercontent.com/26732044/224196447-073197b6-9324-4c42-bd46-3b77f374f47b.png">
