### ISSUE TITLE
Interactive Icon

### ISSUE THREAD

**Issue by JameelKhan9** [phosphor-icons/homepage#214]
I saw there were some cursors, but it would be good to have some cursors with `interactive` meaning.

<img width="33" alt="image" src="https://user-images.githubusercontent.com/59159249/217786691-0e2ff579-8ef9-4dd2-84d8-a69a53d59647.png">

<img width="30" alt="image" src="https://user-images.githubusercontent.com/59159249/217786971-7349d257-0a03-4553-ac0f-96a1d3c5cdb9.png">

**Comment by rektdeckard** [comment]
Added `cursor-click` in v2.0.0
