### ISSUE TITLE
Gear icon not clear

### ISSUE THREAD

**Issue by JameelKhan9** [phosphor-icons/homepage#215]
**Describe the bug**
The current gear icon, has had some feedback by users as looking closer to a flower or sun at smaller sizes than a gear. Can the current gear have the spokes more sharper?

**To Reproduce**
1. See "gear" in icon library:
<img width="199" alt="image" src="https://user-images.githubusercontent.com/59159249/218029271-7392ee8d-9956-4a25-a87c-f39d61b6cad2.png">

**Expected behavior**
User is able to clearly identify gear icon for settings or machinery.

**Comment by rektdeckard** [comment]
Thank for the request, @JameelKhan9 . We have a new iOS-style toothed gear setting icon landing in the next release.

**Comment by rektdeckard** [comment]
Added `gear-fine` in v2.0.0
