### ISSUE TITLE
Mastodon Logo

### ISSUE THREAD

**Issue by birobirobiro** [phosphor-icons/homepage#216]
**Describe the requested icon**
Mastodon logo

**Screenshots**
![image](https://user-images.githubusercontent.com/22185823/218735377-77e49c05-2e01-4030-8d71-9cc7714d1e34.png)
![image](https://user-images.githubusercontent.com/22185823/218735407-50287e54-7fec-464f-a523-b97c86c23cf7.png)
![image](https://user-images.githubusercontent.com/22185823/218735422-3da461c4-a866-4a64-a3cf-fc823d0ba95a.png)

**Additional context**
[Add any other context here.](https://joinmastodon.org/branding)

**Comment by ThatOneCalculator** [comment]
While a Mastodon logo would be great, let's not forget about the entire Fediverse! Mastodon is just one piece of software on the entire network.

Fediverse logo:

![image](https://user-images.githubusercontent.com/44733677/224512682-db5cd589-4496-45ad-944a-3749cf51209f.png)

**Comment by tiagorangel2011** [comment]
+1, really great idea!

**Comment by teotimepacreau** [comment]
> **Describe the requested icon** Mastodon logo
> 
> **Screenshots** ![image](https://user-images.githubusercontent.com/22185823/218735377-77e49c05-2e01-4030-8d71-9cc7714d1e34.png) ![image](https://user-images.githubusercontent.com/22185823/218735407-50287e54-7fec-464f-a523-b97c86c23cf7.png) ![image](https://user-images.githubusercontent.com/22185823/218735422-3da461c4-a866-4a64-a3cf-fc823d0ba95a.png)
> 
> **Additional context** [Add any other context here.](https://joinmastodon.org/branding)

+1

**Comment by viktorix** [comment]
Yes, please.

**Comment by nithou** [comment]
Only missing piece for me 🙏🏻

**Comment by enricogallesio** [comment]
This would be fantastic!

**Comment by ThatOneCalculator** [comment]
Given their styles are very similar, I think Phosphor could use the Fediverse, Mastodon, Firefish, Misskey, Pixelfed, GoToSocial, Akkoma, and Pleroma icons from Arcticons. (Full disclosure, I designed the Firefish/GTS/Akkoma/Pleroma ones, and helped with the Fediverse one.)

<table>
<tr>
 <td><img src="https://raw.githubusercontent.com/Donnnno/Arcticons/main/icons/white/fediverse.svg" height="100" /></td>
<td><img src="https://raw.githubusercontent.com/Donnnno/Arcticons/main/icons/white/mastodon.svg" height="100" /></td>
<td><img src="https://raw.githubusercontent.com/Donnnno/Arcticons/main/icons/white/firefish.svg" height="100" /></td>
<td><img src="https://raw.githubusercontent.com/Donnnno/Arcticons/main/icons/white/misskey.svg" height="100" /></td>
<td><img src="https://raw.githubusercontent.com/Donnnno/Arcticons/main/icons/white/pixeldroid.svg" height="100" /></td>
<td><img src="https://raw.githubusercontent.com/Donnnno/Arcticons/main/icons/white/akkoma.svg" height="100" /></td>
<td><img src="https://raw.githubusercontent.com/Donnnno/Arcticons/main/icons/white/pleroma.svg" height="100" /></td>
<td><img src="https://raw.githubusercontent.com/Donnnno/Arcticons/main/icons/white/gotosocial.svg" height="100" /></td>
<tr>
 <td><img src="https://raw.githubusercontent.com/Donnnno/Arcticons/main/icons/black/fediverse.svg" height="100" /></td>
<td><img src="https://raw.githubusercontent.com/Donnnno/Arcticons/main/icons/black/mastodon.svg" height="100" /></td>
<td><img src="https://raw.githubusercontent.com/Donnnno/Arcticons/main/icons/black/firefish.svg" height="100" /></td>
<td><img src="https://raw.githubusercontent.com/Donnnno/Arcticons/main/icons/black/misskey.svg" height="100" /></td>
<td><img src="https://raw.githubusercontent.com/Donnnno/Arcticons/main/icons/black/pixeldroid.svg" height="100" /></td>
<td><img src="https://raw.githubusercontent.com/Donnnno/Arcticons/main/icons/black/akkoma.svg" height="100" /></td>
<td><img src="https://raw.githubusercontent.com/Donnnno/Arcticons/main/icons/black/pleroma.svg" height="100" /></td>
<td><img src="https://raw.githubusercontent.com/Donnnno/Arcticons/main/icons/black/gotosocial.svg" height="100" /></td>
<tr>
 <td>Fediverse</td>
<td>Fediverse</td>
<td>Fediverse</td>
<td>Fediverse</td>
<td>Fediverse</td>
<td>Fediverse</td>
<td>Fediverse</td>
<td>Fediverse</td>
</table>

**Comment by ThatOneCalculator** [comment]
@rektdeckard is there any chance we could get an update on this? It seems to be pretty highly requested.

**Comment by ThatOneCalculator** [comment]
Here's my best attempt at the Fediverse, Mastodon, Firefish, Misskey, and Pixelfed logos in the Phosphor style. Feel free to use or remix them, these renditions of the aforementioned logos below are MIT licensed.


<table>
<tr>
<td><img src="https://github.com/phosphor-icons/homepage/assets/44733677/d97128fb-8b11-463c-bf4d-f26d827c0e23" height="100" /></td>
 <td><img src="https://github.com/phosphor-icons/homepage/assets/44733677/06ed98db-f909-44c2-ac85-32c7517629bc" height="100" /></td>
<td><img src="https://github.com/phosphor-icons/homepage/assets/44733677/d0e0f0a3-ae77-44ec-a14b-8fa5c94cbb00" height="100" /></td>
<td><img src="https://github.com/phosphor-icons/homepage/assets/44733677/26021d7b-2e12-417d-8b42-4771ed7ef093" height="100" /></td>
<td><img src="https://github.com/phosphor-icons/homepage/assets/44733677/f90be7d5-f831-4d2d-838e-9432551d982b" height="100" /></td>
<td><img src="https://github.com/phosphor-icons/homepage/assets/44733677/75bfd66e-6c8f-4840-8073-a4995cc30e32" height="100" /></td>
<td><img src="https://raw.githubusercontent.com/phosphor-icons/core/main/raw/regular/twitter-logo.svg" height="100" /></td>
<tr>
<td>🆕 <code>fediverse-logo</code></td>
<td>🆕 <code>mastodon-logo</code></td>
<td>🆕 <code>firefish-logo</code></td>
<td>🆕 <code>misskey-logo</code></td>
<td>🆕 <code>pixelfed-logo</code></td>
<td>🆕 <code>friendica-logo</code></td>
<td><code>twitter-logo</code></td>
</table>

**Comment by rektdeckard** [comment]
Thanks @ThatOneCalculator. We're including Mastodon and Fediverse logos for sure in the next release, and may consider including others of this list. As a rule, we don't stick to strict release cycles, and don't make promises on release dates, but rest assured that then next update is in progress.

**Comment by inakicalvo** [comment]
I'd love to have the Mastodon logo too!

**Comment by rektdeckard** [comment]
Added and `mastodon-logo` `fediverse-logo` in [v2.0.1](https://github.com/phosphor-icons/homepage/releases/tag/v2.1.0)

**Comment by gBasil** [comment]
Would it be good to add an `activitypub` tag to the fediverse logo?

**Comment by ThatOneCalculator** [comment]
ActivityPub has a different logo than the Fediverse

![image](https://github.com/phosphor-icons/homepage/assets/44733677/d26ec071-4799-402b-83ab-d4041d54744b)

**Comment by rektdeckard** [comment]
@ThatOneCalculator thanks for pointing that out. This ticket was about a mastodon logo. It might be helpful to spin off a new ticket for each of the fediverse-oriented icons you're looking for. We can't and won't get to all of them at once, so having them separate helps us gauge interest on a case-by-case basis.

**Comment by ThatOneCalculator** [comment]
I don't think an ActivityPub logo is all that necessary tbh

**Comment by gBasil** [comment]
> ActivityPub has a different logo than the Fediverse
> 
> ![image](https://private-user-images.githubusercontent.com/44733677/318294229-d26ec071-4799-402b-83ab-d4041d54744b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5MjQzNzgsIm5iZiI6MTcxMTkyNDA3OCwicGF0aCI6Ii80NDczMzY3Ny8zMTgyOTQyMjktZDI2ZWMwNzEtNDc5OS00MDJiLTgzYWItZDQwNDFkNTQ3NDRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMxVDIyMjc1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1M2IyZjBlZGY4ZTJkOTBlNDliMDNkY2Y0N2I1NDZmY2E5OThmMDEyOTI5NTdlMmI5MGZmZTJkMWU2NzkzNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uZLIdT_zMhXT4JVPaKqrGFHxAkR2oy0e3PQe08QwuCs)

Gotcha. There's a close association with ActivityPub and the fediverse though, and I'm pretty sure the tags are intended to make things more easily searchable.

**Comment by rektdeckard** [comment]
See #512 for anyone interested in following discussion on other fediverse logos.
