### ISSUE TITLE
[Question] How to change the SVG color with css since latest release?

### ISSUE THREAD

**Issue by rylanharper** [phosphor-icons/homepage#223]
First of all, congrats on the new 2.0 release! This is my favorite icon library BY FAR and have used it on a ton of my projects!:)

**Describe the bug**
Not necessarily a bug, but I noticed that since well, yesterday, the icons do not have a set stroke-color (`stroke="#000000"`) any longer.. I normally use svg strokeColors for hover interactions in CSS by setting the stroke to `stroke="currentColor"` and then doing something like this with css (using tailwind/unocss `@apply` in this example):
```
// The svg would be a black color initially
// then gray on when a user hovers over the svg
button {
  @apply flex p-2;
  @apply text-black transition duration-300 ease;

  svg {
    @apply w-6 h-6;
  }

  &:hover {
    @apply text-gray-500;
  }
}
```

**Additional context**
Is there any way to easily change the svg color with a css hover/focus animation now? Thanks!

**Comment by rektdeckard** [comment]
Hey @rylanharper! yes, some implementation details have changed with the 2.0 release. If you're using the SVG assets directly, `fill` is now the attribute/property for manipulating color rather than `stroke` since we have moved to using smaller, minified paths. This is a feature, not a bug 😆 

I'm not sure what you mean by "inner-color", as we don't have distinctive layers, except in the case of `duotone` icons. If you share a screenshot of before/after maybe I can help?

**Comment by rylanharper** [comment]
Hey @rektdeckard, yes what I am doing is similar to duotone, but with a solid "inner" color fill rather than a lowered opacity. Here is a simple screen shot with the Phosphor heart icon - when the user clicks the heart the inner color of the heart turns yellow:

<img width="54" alt="Screenshot 2023-03-09 at 9 07 01 AM" src="https://user-images.githubusercontent.com/16216160/224102305-fab1e1a6-1182-4589-8454-e4edcb1d2746.png">

Currently I am using the raw svg from the old version to simply add `fill="#ffcc30"` (yellow color) to the `<path>`, but when I tried doing something similar to the new icon variants (adding a fill to the `<path>`) only the outline changes.

**Comment by rektdeckard** [comment]
Yup! you can target the duotone layer via some careful CSS selectors, based on the fact that the duotone layer is always at 0.2 opacity:

```html
<style>
.duocolor [opacity="0.2"] {
  opacity: 1;
  fill: yellow;
}
</style>
<svg class="duocolor" ...>
  ...
</svg>
```

I tested an example of this using our React library, and it works great:
https://stackblitz.com/edit/react-ts-kvdzu1?file=App.tsx

Implementation would be quite similar from vanilla HTML.

**Comment by rylanharper** [comment]
@rektdeckard Wow, this is exactly what I needed. I got my svgs working now. Really appreciate the help with this question.. Also thanks for all the work that goes into making this library!
