### ISSUE TITLE
Vectorisation limits icon possibilities

### ISSUE THREAD

**Issue by elise-lcdb** [phosphor-icons/homepage#227]
Hello! Congratulations on the 2.0 release! There are many cool icons that I'm excited to see.

I have noticed that the Figma file, and the SVG files from your site are only available in vectors. While there are probably several practical reasons why you have chosen to switch to vectors, I find that it limits the possibilities of what an be done with your icons.

Before, it was easy to change each individual path/circle etc to have its own style which appears to no longer be possible with the choice to move to vectors. 

Here is an example of an everyday use case in the majority of the projects I work on.

![CleanShot 2023-03-10 at 15 45 55](https://user-images.githubusercontent.com/31904512/224346185-c7d78c3b-78ee-4f11-b18b-9cf77f7e0412.png)

The same can be applied for the new Caret Up Down. I would love to integrate it in my app as a filter button, and have the "active caret" in one color and the other caret in an "inactive" color. 

![CleanShot 2023-03-10 at 15 55 58](https://user-images.githubusercontent.com/31904512/224348136-73d2d12b-ef29-4e3f-b5eb-b3ac63f26807.png)

Is the switch to vectorisation permanent?

**Comment by rektdeckard** [comment]
Hey @elise-lcdb! The vast majority of users have asked for us to ship flattened icons, and we listened to the feedback. In most cases this is all people need, and it makes it easier to scale and color without having to worry about accidentally modifying an icon. It also seems to be the standard format for distributing, and results in smaller overall file size, so the decision is here to stay.

BUT! There are still tons of ways to still get the Raw assets if you need them. We have always included both Raw and Flattened SVGs in our asset kit, which is what you get by clicking the [Download](https://phosphoricons.com/assets/phosphor-icons.zip) link on our site. They can also be found individually in the [@phosphor-icons/core](https://github.com/phosphor-icons/core/blob/main/raw) repository. Our Figma plugin gives you the option to choose whether you want Raw or Flat.

If you tell me how you typically use Phosphor, maybe we can make it easier for you to get to the raw assets! Are you using the "Copy SVG" function on our website?

**Comment by peter13peter** [comment]
Hi! Will it be possible to have the same option to choose between raw and flat in the Sketch plugin as well? Thank you!

**Comment by rektdeckard** [comment]
@peter13peter soon, yes
