### ISSUE TITLE
GithubLogo icon

### ISSUE THREAD

**Issue by eidynho** [phosphor-icons/homepage#229]
**Describe the bug**
I'm using phosphor-react and GithubLogo icon is in different format than appears on phosphoricons website.

**To Reproduce**
```
import { GithubLogo } from "phosphor-react";

export function ExampleGithubLogoIcon() {
    return <GithubLogo size={32} color="#f0f0f0" />;
}

```

**Expected behavior**
The icon that appears on phosphoricons website.

**Screenshots**
The icon that I got is this:
![image](https://user-images.githubusercontent.com/83616523/224853077-fd38bc02-2124-4381-93a9-1b5eb7bc1240.png)

GithubLogo in Phosphoricons website:
![image](https://user-images.githubusercontent.com/83616523/224853436-ab2fccf9-7189-48c7-ad3e-ec3b11e5a1a2.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: v110

**Comment by rektdeckard** [comment]
Not a bug. The icon was revised in v2.0.
