### ISSUE TITLE
News icons for Flutter

### ISSUE THREAD

**Issue by wesleytoshio** [phosphor-icons/homepage#234]
I noticed that the icons that contain a red ball are not available for Flutter, obviously because the package has not been updated yet. Do you have any predictions? Thanks in advance. Nice package

**Comment by rektdeckard** [comment]
As you've probably seen, `phosphor-flutter` has been updated to 2.0. Closing as complete.

**Comment by rektdeckard** [comment]
Please leave future flutter-related issues on that repo, thanks!
