### ISSUE TITLE
Icon request: map-pin-plus

### ISSUE THREAD

**Issue by RamoFX** [phosphor-icons/homepage#245]
Dear `phosphor-icons` developers, designers and other contributors,

First of all I would like to thank you all very much for your incredible icons. They are amazing looking, intuitive for user, and easy to be integrated in libraries and frameworks.

I would like to request a `map-pin-plus` icon, that would contain existing `phosphor-icons`'s `map-pin` icon, but with the plus symbol. I image the plus symbol being in the bottom right corner. In duotone variant, I personally do not think it is necessary to fill the plus symbol.

Similarly, there is `file` icon and the `file-plus` variant.

For example, if you are making an application that deals with some locations or places, the "add location" button could contain `map-pin-plus` and it would be more descriptive than just 'plus' icon. I believe there are more examples, where this icon would be useful, this is just one example.

Thanks!

**Comment by rektdeckard** [comment]
Thanks @RamoFX! Happy to add this to the list :)
