### ISSUE TITLE
Clear text styles

### ISSUE THREAD

**Issue by AdrianFahrbach** [phosphor-icons/homepage#247]
**Describe the requested icon**
An icon that for an button that removes styling from text. This is useful for e.g. rich text editors.

**Screenshots**
![screenshot 2023-04-10 at 02 18 50@2x](https://user-images.githubusercontent.com/45072099/230803430-47a6f89d-9660-48da-a878-394bda1013a3.jpg)

**Additional context**
* This request is related to #246.
* There is no standard for this kind of icon, but it seems like the example in my screenshot is the most popular one (see [google search results](https://www.google.com/search?q=remove+text+styling+icon&tbm=isch&ved=2ahUKEwi3-IevhZ7-AhW6kf0HHf4ZC9IQ2-cCegQIABAA&oq=remove+text+styling+icon))
* I attached my own version of this icon which is based on `text-t`

![clear-text-styles](https://user-images.githubusercontent.com/45072099/230803583-8a2ba6d6-4a98-46a0-bded-f0a19035b483.svg)

**Comment by rektdeckard** [comment]
We're going to go ahead with `text-t-slash` as requested in #277, hope this works.
