### ISSUE TITLE
Icon request: ScreenShare 

### ISSUE THREAD

**Issue by m1gu3l** [phosphor-icons/homepage#248]
**Describe the requested icon**
Arrow from ![image](https://user-images.githubusercontent.com/140639/231976937-9d6db42c-7815-4d88-893f-28ea7cf3f37d.png) + ![image](https://user-images.githubusercontent.com/140639/231977100-cc9034b2-fe92-4811-b010-3a2cbaedd3b3.png)

**Comment by rektdeckard** [comment]
Added as `monitor-arrow-up`
