### ISSUE TITLE
FR: add currentcolor as option in color picker 

### ISSUE THREAD

**Issue by wesort** [phosphor-icons/homepage#249]
**Describe the feature request**
An option to set the color value as `currentcolor` which in turn sets the `fill` attribute's value.

**Additional context**
The `currentcolor` value allows the SVG to inherit the `color` property ([MDN docs](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#currentcolor_keyword)). This is particularly useful when icons are set within a site with color theming or when using Tailwind CSS.

**Comment by rektdeckard** [comment]
@wesort Do you think it would be intuitive to have this be the default behavior if the preview color is set to `#000000`, rather than adding an explicit button to do so?

**Comment by rektdeckard** [comment]
Also, FWIW, `currentColor` is used in the assets when you download the entire asset kit. We don't do it when you download an individual icon, because it feels more expected to have those match your current preview settings.

**Comment by wesort** [comment]
I think having `currentcolor` is the most neutral and intuitive option. Especially as `#000000` is what browser's set initially for the `color` property.

Though of course I can only comment from my own individual perspective, I _always_ want single colour SVGs to use `currentcolor`. This allows the asset to be flexibly styled with CSS elsewhere in the markup. And I like that you're using opacity on the secondary color of the duotone versions. 

Thanks.

**Comment by rektdeckard** [comment]
I appreciate and understand what you're asking for, but I would argue that WYSIWYG is what most would expect. In fact, feedback we got in the past on this matter is actually why it has the behavior it does.

For your use case, I recommend using basically any other means of sourcing our icons -- download the asset kit, use one of our packages for your framework, or one of the framework-agnostic packages like [@phosphor-icons/core](https://github.com/phosphor-icons/core), [@phosphor-icons/web](https://github.com/phosphor-icons/web) or [@phosphor-icons/webcomponents](https://github.com/phosphor-icons/webcomponents). All of these use `currentColor` by default, or are based on icon fonts and thus inherit color in the same way.

If we get similar feedback on the matter, we can consider adding a toggle of some kind, but we already have quite a few controls on the site, and do not wish to overcomplicate it.

**Comment by rektdeckard** [comment]
Alternately, I can add it is as a hidden power-user feature: maybe right-clicking the color picker would set the color to `currentColor`? This would unlock the behavior you need, but not require any redesign. WDYT?

**Comment by wesort** [comment]
Looks to me like you've already done this! 

Fantastic idea, works perfectly. Thank you.
