### ISSUE TITLE
Chest / loot box icon

### ISSUE THREAD

**Issue by lolouthefox** [phosphor-icons/homepage#253]
**Describe the requested icon**
The requested icon would be a chest icon that could also work as a loot box icon. The best would be from the front, I think it's easier to understand.

**Screenshots**
![image](https://user-images.githubusercontent.com/96738841/233107068-1d90ff05-636a-4657-b750-3e5c0755a1de.png)

**Additional context**
I'd personally use it in my video games' store website for purchasable items such as _loot boxes_ that could be represented with a chest. That'd be also handy in a lot of situations like an inventory etc...

**Comment by srabouin** [comment]
I would love to see a chest icon as well :)

Here are some additional examples if this helps!

https://react-icons.github.io/react-icons/search/#q=chest
https://fontawesome.com/icons/treasure-chest?f=sharp&s=regular

**Comment by rektdeckard** [comment]
It's coming 👍
