### ISSUE TITLE
Network Icon

### ISSUE THREAD

**Issue by sachaw** [phosphor-icons/homepage#256]
**Describe the requested icon**
An icon(s) to convey a conceptual network or an ethernet connection,
There could also be a slash or cross version to indicate a lack of connectivity, like `wifi-x`

**Screenshots**
![network](https://user-images.githubusercontent.com/11172820/234118417-814c6fb7-ec17-4bac-899a-4b988b7cf993.svg)

**Comment by rektdeckard** [comment]
`graph`, `share-network`, `tree-structure` do none of these work?

**Comment by rektdeckard** [comment]
Though I don't think we have slashed versions of any of those.

**Comment by sachaw** [comment]
They have some overlapping functionality, but it should also be able to convey the presence of an IP network or generic wired network

**Comment by pimterry** [comment]
+1. Just to add context on the "existing alternatives" point: all the existing alternatives are either more generic than a computer network (graphs, tree structures) or have existing common semantics in software (the share icon) that would cause confusion.

I'm building developer tools, and I'm looking for a icon to illustrate "local wired network connection" specifically (as opposed to lots of other types of connections and devices). I don't have an immediate need for a slashed version but I can easily imagine use cases in future.

An icon to illustrate this more precisely would be great. I think [font-awesome's take](https://fontawesome.com/icons/network-wired) (three boxes all connected to a wire along the middle) is good, and very similar patterns seem to be used in most icon sets elsewhere ([Lucide](https://lucide.dev/icons/network), [Iconoir (under 'Connectivity')](https://iconoir.com/), [Google Icons](https://fonts.google.com/icons?selected=Material+Symbols+Outlined:lan:FILL@0;wght@400;GRAD@0;opsz@24&icon.query=network)). I'd love to see a Phosphor version.

**Comment by rektdeckard** [comment]
Totally. We're including true `network` and `network-slash` in the upcoming release.
