### ISSUE TITLE
Video call/meeting icon

### ISSUE THREAD

**Issue by StanFromTraction** [phosphor-icons/homepage#263]
**Describe the requested icon**
An icon depicting the concept of a video call. Could include 1 or 2 people and a screen or camera.

Example: sideview of 2 people facing a vertical line (that represents a screen from the side)

**Additional context**
Useful for "Contact us" icons on websites, if the contact methods isn't chatting nor a phone call, but a video call.

**Comment by ThatOneCalculator** [comment]
Probably already covered by `video-camera` or `webcam`
