### ISSUE TITLE
Downloaded PNG icon size

### ISSUE THREAD

**Issue by moonflowcr** [phosphor-icons/homepage#264]
This isn't a bug or anything, but more like a request that might be useful to other users. I wanted to know what happened to the size of the icons I download in PNG format. I use those as icons in my personal Notion because those were big enough (512x512 px) without having to adjust the size in the slider in the bar, but now I downloaded new ones with the same color and style individually and they're noticeably smaller even in the maximum size (96x96). 

Would the team consider to go back to the old size mentioned above or at least offer different size options when you download it, like other websites do?

**Comment by rektdeckard** [comment]
Hi @moonflowcr. For consistency the PNG downloads now adopt all the preview settings, including the size you are currently previewing at.

If you absolutely need PNGs, you can download the whole asset kit. But there is a much better way to use Phosphor in Notion: in the panel on the bottom, click the overflow arrow and copy as "Data SVG". You can then go to the Custom tab when picking a pake icon in Notion, and paste into the URL input. This will use a vector icon and avoids any concern over resolution / size.
