### ISSUE TITLE
Subject Icons

### ISSUE THREAD

**Issue by marcoscocacode** [phosphor-icons/homepage#265]
**Describe the requested icon**
I would like some icons referring to some subject such as Medicine, Psychology, among all others... It's pretty hard to find something that covers most of them by the same standard, so it would be very good to see.

**Screenshots**
![mental-health](https://user-images.githubusercontent.com/73766081/237008995-92bfa131-56b5-4e44-87c3-e85a318bce98.png)
![caduceus-symbol](https://user-images.githubusercontent.com/73766081/237009010-bd345015-6478-41aa-81d3-050c857514e3.png)
![nutrition (1)](https://user-images.githubusercontent.com/73766081/237009266-06bfc123-bace-4102-bf20-ca8d665ef6ec.png)
![computer-science](https://user-images.githubusercontent.com/73766081/237009565-2935cbb1-cb1f-49d0-afdf-ed078881a37d.png)

**Comment by rektdeckard** [comment]
We have a number of icons that can be used to represent a lot of the core subjects: `brain` for psychology, `atom` for physics, `stethoscope` and many others for medicine, along with plenty of academia related icons. Will these work for you? Are there specific symbols you do *not* find represented?

**Comment by rektdeckard** [comment]
Closing as stale.
