### ISSUE TITLE
Animating icons

### ISSUE THREAD

**Issue by its-monotype** [phosphor-icons/homepage#271]
It's not possible to animate these icons using `stroke-dasharray` `stroke-dashoffset` since they not using stroke? Are there any plans to change this?

**Comment by its-monotype** [comment]
@rektdeckard Any thoughts?

**Comment by rektdeckard** [comment]
Yeah, everything is a tradeoff here. We moved to using `path` elements only, and in doing so saved >30% on the bundle size and simplified a lot of common CSS style overrides quite a lot...but you can no longer do this animation trick.

I don't think we will walk back that decision, unfortunately. But you might look into using [@phosphor-icons/core](https://github.com/phosphor-icons/core), which does expose the raw stroke assets. It wouldn't be readymade react components, but you could work out a custom solution.
