### ISSUE TITLE
Add new helicopter icon

### ISSUE THREAD

**Issue by joaovrcosta** [phosphor-icons/homepage#272]
**Describe the requested icon**
I would like a helicopter icon because I work with airline websites and these icons can only be downloaded in png, I would like it in the library

**Screenshots**
![image](https://github.com/phosphor-icons/homepage/assets/70654718/d374e834-b2c5-4281-8fa2-55cacc5df547)

**Additional context**
Add any other context here.

**Comment by Samuel-Webster** [comment]
I tried to look for this but can't seem to find it, if it is missing I would like to request a helicopter icon in the same style "airplane" icon. Love these icons by the way.
