### ISSUE TITLE
Steam Icon

### ISSUE THREAD

**Issue by Retr0-01** [phosphor-icons/homepage#274]
**Describe the requested icon**
I would like to have a Steam icon added. Steam (https://store.steampowered.com/) is the best and most known gaming platform and game distribution system.

**Screenshots**
![image](https://github.com/phosphor-icons/homepage/assets/61121754/c21509f7-22a9-4447-b22a-e15a2ce6bc36)

**Comment by rektdeckard** [comment]
Closing as duplicate of #219, but we're on it!
