### ISSUE TITLE
[Suggestion] Export icons by weight

### ISSUE THREAD

**Issue by oguzgelal** [phosphor-icons/homepage#282]
Thanks for the great icons!

Given that the following are the props of `Icon`:
```ts
{
  alt?: string;
  color?: string;
  size?: string | number;
  weight?: IconWeight;
  mirrored?: boolean;
}
``` 

I feel like `weight` would better fit as an "icon set" / way to categorize icons than a prop on each individual icon. All other props makes sense on a per-instance basis, but IMO it's a rarer use case for weight. Like one would pick a weight that's a good fit for their design system, and use it everywhere, except from a few instances maybe - at least that's how I've been using it. It's uncomfortable to always pass say `weight="duatone"` every time I use an icon somewhere in the code, which is why I have a wrapper component that applies `weight` to every instance unless specified otherwise. 

I think it'd be much more comfortable if we'd be able to import icons by weight, and the weight would be applied. So for instance:

```ts
// instead of this:
import { CaretDown } from "@phosphor-icons/react";
<CaretDown weight="duatone" />

// this would be easier:
import { CaretDown } from "@phosphor-icons/react/duatone";
<CaretDown />
```

**Comment by rektdeckard** [comment]
A very common pattern is to use different weights for "stateful" icons, I.E. regular/fill -> enabled/disabled. If you want a foolproof way to adopt default styles across all icons, use the `IconContext` we provide with the react library and wrap the root of your app with it:

```tsx
import { IconContext, CaretDown } from "@phosphor-icons/react";

function App() {
  return (
    <IconContext.Provider value={{ weight: "duotone" }}>
      {/* All icons in here are duotone */}
      <CaretDown />
    </IconContext.Provider>
  );
}
```

Also in future, please submit all issues specific to the React package over on that repo.
