### ISSUE TITLE
Flexibile icon

### ISSUE THREAD

**Issue by michaelmartinelli** [phosphor-icons/homepage#290]
**Describe the requested icon**
An arrow that splits into three arrows, indicating the ability to adapt or branch out into different directions

**Screenshots**
![360_F_235384880_KPxo2B0vGkIFKuymuv6nzLa6L5hw62xG](https://github.com/phosphor-icons/homepage/assets/49559802/1dae0fa9-43c5-42d1-a3d0-2ec98ec56fbe)

**Comment by rektdeckard** [comment]
Would `arrows-split` or `git-branch` suit your needs?

**Comment by rektdeckard** [comment]
Also `graph`, `tree-structure`
