### ISSUE TITLE
an icon related to buildings

### ISSUE THREAD

**Issue by WesleyDev184** [phosphor-icons/homepage#291]
**Describe the requested icon**
a few icons related to buildings and would like a few more varieties

**Screenshots**
![image](https://github.com/phosphor-icons/homepage/assets/57929638/deb746d7-91eb-4479-b2b5-bdca79df9a41)

**Comment by dolmios** [comment]
There is an icon called _Buildings_ that's pretty similar to this, short of having nice trees out the front. How would you suggest extending on this?

https://github.com/phosphor-icons/core/blob/main/raw/regular/buildings.svg
