### ISSUE TITLE
Feature request: raw svg download instead of copy on phosphor-icons site

### ISSUE THREAD

**Issue by massimo-cassandro** [phosphor-icons/homepage#296]
I think it would be much more convenient to be able to download the raw format instead of copying it, or at least give the choice of copy or download.

Thanks

**Comment by joaoaoluiz** [comment]
That would be great, I used to use icon-sets.iconify.design/ph/ just for this feature

**Comment by rabeehrz** [comment]
I think this already exists?
<img width="303" alt="Screenshot 2023-07-27 at 10 24 10 PM" src="https://github.com/phosphor-icons/homepage/assets/44024553/6be00eae-a0af-42d0-bcd4-5ab9f5085b04">

**Comment by rektdeckard** [comment]
@massimo-cassandro this is something we can definitely add! I'll try to push a quick update this weekend.
@rabeehrz that option will download the *flattened* SVG, I.E. one containing only a single `<path>` element describing the icon shape.
