### ISSUE TITLE
Some hobbies and work related icons

### ISSUE THREAD

**Issue by scoinnotec** [phosphor-icons/homepage#298]
**Describe the requested icon**

cable car

wood log
wood board
concrete
iron bar / metal bar

locksmith
tinsmith
gutter
plumber
tube

construction site
crane
mason's trowel
concrete mixer

airbrush
paint spray gun

stove
chimney

tiler
tile

mechatronics

farm
farmer

cook
chef hat

mountain rescue
ambulance
fire department

---------------------------

skiing
toboggan
cross country skiing
snowboarding

model making
model railroad
remote control car

sudoku
crossword puzzle
lego
dance
disco
trumpet
knitting
netflix

hiking
climbing
yoga

**Additional context**

thank you so much for your great work and this fantatic icon set.
it would be great if some of the icons mentioned above could be realized.

**Comment by rektdeckard** [comment]
Added `cable-car`, `log`, `pipe`, `pipe-wrench`, `hard-hat`, `crane`, `crane-tower`, `truck-trailer`, `bulldozer`, `tractor`, `farm`, `person-simple-ski`, `person-simple-snowboard`, `person-simple-swim`, `person-simple-tai-chi`, `checkerboard`, `lego`, `lego-smiley`, `disco-ball`, `yarn`
