### ISSUE TITLE
Category Icon

### ISSUE THREAD

**Issue by RishabhDesigns** [phosphor-icons/homepage#301]
There is no icon available for category.

**Comment by rektdeckard** [comment]
What would this look like, in your mind?

**Comment by staffanmowitz** [comment]
Here's what category icons look like in other icon libraries. So perhaps something along those lines?

![Screenshot 2023-10-19 at 12 14 07@2x](https://github.com/phosphor-icons/homepage/assets/4193622/7c342d3d-3e9b-45ce-b9ab-8af6f6b53cf3)

https://react-icons.github.io/react-icons/search?q=category

**Comment by rektdeckard** [comment]
We have `shapes`, `squares-four`, `circles-four`. Does this work for you? I can update the tagging so they are found if you search "categories".

**Comment by staffanmowitz** [comment]
`squares-four` works good for me!

I think it would be a good idea to add "categories" as a tag for all the icons you suggested.

**Comment by RishabhDesigns** [comment]
It could be like this.

![image](https://github.com/phosphor-icons/homepage/assets/140587913/8e9454f0-afa3-402e-bc3e-90e2fe8e00e2)

![image](https://github.com/phosphor-icons/homepage/assets/140587913/af17e29a-482b-4216-9c3f-212b527b3f09)

![image](https://github.com/phosphor-icons/homepage/assets/140587913/b61b86c0-23fb-4815-8c4d-ad40379fa8b9)

In my opinion icon shapes needs to be different. It doesn't need to be 4 squares or 4 circles.

**Comment by rektdeckard** [comment]
Again, we have the `shapes` icon which is similar to your last example image.
