### ISSUE TITLE
Nextjs 13 support?

### ISSUE THREAD

**Issue by mthmcalixto** [phosphor-icons/homepage#302]
**Describe the bug**

**To Reproduce**
1. Add icon to code
2. Open browser

**Expected behavior**
Work

**Screenshots**
![Screenshot_5](https://github.com/phosphor-icons/homepage/assets/121470728/8dd6ec00-5406-440a-9af6-b8c1a9b24f98)

**Comment by jln13x** [comment]
bump

**Comment by rektdeckard** [comment]
Experimental support for Next 13 / RSC added in v2.1.3. See https://github.com/phosphor-icons/react/pull/64 

If you have more comments specific to the React package, please make an issue over there
