### ISSUE TITLE
Add Petanque Sport Icon (french Petanque)

### ISSUE THREAD

**Issue by glucoz** [phosphor-icons/homepage#305]
Hi,

Hello,

Is it possible to add an icon for the sport "Pétanque" (Pétanque Française).
We have prepared SVGs (full icon and version for Duotone).
Thank you

![petanque](https://github.com/phosphor-icons/homepage/assets/1334418/3fc27414-f9cc-434c-b906-7b708b5a4560)
![Union](https://github.com/phosphor-icons/homepage/assets/1334418/77d05c43-e918-4eed-b2dc-ee3cb0e10484)
![Vector](https://github.com/phosphor-icons/homepage/assets/1334418/9a4f83f0-427d-4a03-8d4b-8c73ddfeefb8)
**Describe the requested icon**
Explain the icon you'd like to see, and potential use-cases.

**Screenshots**
If applicable, add screenshots to help illustrate the icon appearance.

**Additional context**
Add any other context here.

**Comment by rektdeckard** [comment]
Added `boules`
