### ISSUE TITLE
X icon (new Twitter)

### ISSUE THREAD

**Issue by carlosvaldesweb** [phosphor-icons/homepage#309]
**Describe the requested icon**
X is the new twitter

**Screenshots**

![descarga](https://github.com/phosphor-icons/homepage/assets/32969705/5a910826-e694-4d08-b911-85fd93230570)

**Comment by tommyvkessel** [comment]
Yes please! For now I'll use 𝕏 as text, but having this as a Phosphor icon would be nice!

**Comment by jasondainter** [comment]
Any chance this will be updated @carlosvaldesweb - happy to buy you a virtual coffee by way of thank you!

**Comment by rektdeckard** [comment]
Ok friends. It's finally here.
