### ISSUE TITLE
Sharepoint Icon

### ISSUE THREAD

**Issue by RichardJMarsh** [phosphor-icons/homepage#310]
**Describe the requested icon**
An icon used for 'Uploading to Sharepoint'. The user in this case is interested in a cloud icon with text overlay with 'S', similar to the document icons with file types overlaid. The instance the user requested is the 'cloud-arrow-up' - replacing the arrow for an 'S'.

**Comment by rektdeckard** [comment]
We don't really get that specific with our icons, you're free to modify icons that we provide to achieve that!
