### ISSUE TITLE
Solid Arrow Triangles

### ISSUE THREAD

**Issue by RichardBarrett** [phosphor-icons/homepage#315]
**Describe the requested icon**
I noticed that there are no solid simple arrow triangles. I think phosphor icons needs them!

**Screenshots**
![image](https://github.com/phosphor-icons/homepage/assets/1667234/5a3cb066-dcee-407e-8baa-6c67c24c36db)

**Comment by rektdeckard** [comment]
We have these icons, they are called `caret-up` `-down` `left` `-right` and take this appearance in the Fill weight.
