### ISSUE TITLE
Add Suitcase w/ Trolley

### ISSUE THREAD

**Issue by ccruser** [phosphor-icons/homepage#316]
**Describe the requested icon**
Please add a suitcase that is being pushed on an airport trolley

**Screenshots**
For reference you can see this version from Font Awesome for reference https://icon-sets.iconify.design/fa6-solid/cart-flatbed-suitcase/

One closer to the design of Phosphor asesthetic is from the interface icons of FlatIcon: https://www.flaticon.com/free-icon-font/luggage-cart_9247210?page=1&position=23&term=travel&origin=search&related_id=9247210

**Additional context**
Primary use case for interface

**Comment by rektdeckard** [comment]
Added `trolley` and `trolley-suitcase`
