### ISSUE TITLE
Some missing telecom related icons

### ISSUE THREAD

**Issue by Viish** [phosphor-icons/homepage#322]
Hi,

**Describe the requested icon**
In the telecom area, the phone icons are great, but some are missing, such as:

- Calls list (could be a mix of phone and list icons you already have)
- Call transfer (could be a mix of phone and arrow-right)
- Paused call (could be a mix of phone and pause)
- Dialer / numpad (nine or ten squares in a grid with 3 columns for example)
- Screen sharing (it's often an arrow to the top in a square)

Also a voice recording icon (voice message sent though chat) would be great.

**Additional context**
I'm working on https://github.com/BelledonneCommunications/linphone-android and we are considering using your library for our new UI.

Thanks in advance!

**Comment by Viish** [comment]
Hi again,

I also noticed you don't have a chat-text with 'slash' on it, would be a nice addition.

Cheers,

**Comment by rektdeckard** [comment]
What are you thinking of for the "voice recording sent thru chat" icon?

**Comment by rektdeckard** [comment]
All good 👍

**Comment by rektdeckard** [comment]
Your other requests have been put on the docket :)

**Comment by Viish** [comment]
Perfect, thanks a lot!

**Comment by Viish** [comment]
@rektdeckard Do you have an ETA for the next release please? 
It's just to know and be able to organize ourselves.

Thanks in advance.

**Comment by rektdeckard** [comment]
@Viish no ETA, we don't make estimates. But we are currently working on the next release.

**Comment by Viish** [comment]
Ok, thanks for the update.

**Comment by Viish** [comment]
Hi again,

Could you also add chat-slash and chat-plus icons ?

Thanks a lot!

**Comment by Viish** [comment]
Thanks a lot for the new version!
