### ISSUE TITLE
Support TypeScript "moduleResolution": "node16"

### ISSUE THREAD

**Issue by omridevk** [phosphor-icons/homepage#331]
### Description

Description
In [TypeScript 4.7](https://devblogs.microsoft.com/typescript/announcing-typescript-4-7), along the property "module": "node16" that enables ESM features in TypeScript, there are new values for the property "moduleResolution": "node16" and "nodenext".

### Problem Statement/Justification

The problem is that when using the icons in env with typescript configured to use "moduleResolution": "node16" will not work.
see screen shot:
<img width="1294" alt="CleanShot 2023-09-04 at 11 29 46@2x" src="https://github.com/phosphor-icons/homepage/assets/9701896/b803c3ea-66a6-437c-819d-a9baf8f298d6">

**Expected behavior**
Import should work without throwing errors.

**Workaround:**
either use "moduleResolution": "bundler"
or use skipLibCheck: "true"

Both are not a good options in my opinion.

Thanks for the great library.

**Comment by omridevk** [comment]
The solution is to add .js/.mjs extension to all the files. ideally should be both to support all env.

**Comment by rektdeckard** [comment]
We've fixed this in 2.1.3 experimental release. If you have further questions specific to the React package, please make an issue over there!
