### ISSUE TITLE
Leaderboard Icon

### ISSUE THREAD

**Issue by bekirytm** [phosphor-icons/homepage#337]
Hello, my request is for a leaderboard icon

<img width="472" alt="Screenshot 2023-09-10 at 22 49 55" src="https://github.com/phosphor-icons/homepage/assets/36936802/7f73b0fb-c23a-4ea1-b4e5-664ff61939f2">

I hope it will be added.  💯

**Comment by rektdeckard** [comment]
Added as `ranking`
