### ISSUE TITLE
More mathematical symbol icons

### ISSUE THREAD

**Issue by melkstam** [phosphor-icons/homepage#345]
**Describe the requested icon**
Explain the icon you'd like to see, and potential use-cases.

It would be nice to have symbols for some more of the common mathematical symbols. 

Some examples are <, ≤, >, ≥, ≠, ≈, ∈, and ∉.

**Screenshots**

I think the characters are enough!

**Additional context**
N/A

**Comment by jakobskrym** [comment]
@melkstam looks like this is now coming 🚀

**Comment by jakobskrym** [comment]
@melkstam looks like this is now coming 🚀

**Comment by rektdeckard** [comment]
Added `approximate-equals`, `empty`, `greater-than`, `greater-than-or-equal`, `intersection`, `union`, `less-than`, `less-than-or-equal`, `member-of`, `not-equals`, `not-member-of`, subset-of`, `subset-proper-of`, `not-subset-of`, `superset-of`, `superset-proper-of`, `not-superset-of`, `text-subscript`, `text-superscript`, `tilde`, `vector-two`, `vector-three`.
