### ISSUE TITLE
Mastodon icon

### ISSUE THREAD

**Issue by teseu** [phosphor-icons/homepage#348]
**Describe the requested icon**
Since there a new exodus, especially from twitter, mastodon has been more popular every day.

**Screenshots**
An svg file
![mastodon-svgrepo-com](https://github.com/phosphor-icons/homepage/assets/3169307/76fe87a2-ba3c-4f97-9122-fd03e7c1ce04)

**Additional context**
Social media

**Comment by ThatOneCalculator** [comment]
Duplicate of #216

**Comment by teseu** [comment]
I searched as 'icon', I'll close it now, thanks @ThatOneCalculator .
