### ISSUE TITLE
Empty icon

### ISSUE THREAD

**Issue by phatgolo** [phosphor-icons/homepage#349]
**Describe the requested icon**
I would like an empty icon that uses the same space as the other icons. This can be useful if you want to align text and icon with in a menu for instance. 

**Screenshots**
![image](https://github.com/phosphor-icons/homepage/assets/6698469/541c03e4-c926-4bca-8469-db1cb709bc38)

**Additional context**
There are also other scenarios where this can come handy.

**Comment by flamestro** [comment]
Is it possible to achieve the same by adding a empty div with the same width and height?

**Comment by rektdeckard** [comment]
Relates to #16. There's a convenient solution provided there to implement yourself, but for the time being we do not plan to add an Empty icon.
