### ISSUE TITLE
New `paper-plane-right` icon style

### ISSUE THREAD

**Issue by babakfp** [phosphor-icons/homepage#357]
Hi

![image](https://github.com/phosphor-icons/homepage/assets/44144724/e9edb4d4-2a77-4d85-ac73-05630eb974b6)
![image](https://github.com/phosphor-icons/homepage/assets/44144724/35611fb9-3209-4e74-bd0a-727b2f33032e)

Please take a look at the send icon, the first screenshot uses phosphoricons `paper-plane-right` icon and the second screenshot uses heroicons `paper-airplane` icon.

You can search for "Send" and see the icon here: https://heroicons.com

I like heroicons send icon more 🤷‍♂️

**Comment by rektdeckard** [comment]
You're welcome to use Heroicons if you like theirs better!
