### ISSUE TITLE
X icon (old Twitter)

### ISSUE THREAD

**Issue by 5t4r-10rd** [phosphor-icons/homepage#362]
<img width="48" alt="Screenshot 2023-10-23 134820" src="https://github.com/phosphor-icons/homepage/assets/117113049/12913c71-92e5-446f-a45f-c686706587d8">

**Comment by fergusjames** [comment]
Brand toolkit and logo download here: https://about.twitter.com/en/who-we-are/brand-toolkit

**Comment by rektdeckard** [comment]
Closing as duplicate of #309

**Comment by fergusjames** [comment]
@rektdeckard Understood. Am curious why this is "not planned". Is this a principled stand against what has happened at Twitter? Or is it that this needs to await a new version of Phosphor icons?

**Comment by rektdeckard** [comment]
@fergusjames it is planned for the next release. Mobile doesn't have an option to close as duplicate, that's all.
