### ISSUE TITLE
Icons for apps like Visual Studio Code, Photoshop, Illustrator

### ISSUE THREAD

**Issue by MihirGrand** [phosphor-icons/homepage#364]
**Describe the requested icon**
Icons for vscode, and adobe apps like photoshop, illustrator, etc.

**Screenshots**
![Adobe_Photoshop_CC_icon svg](https://github.com/phosphor-icons/homepage/assets/118926177/e4af0554-e249-4277-acd9-872eb35e6924)
![file_type_vscode_icon_130084](https://github.com/phosphor-icons/homepage/assets/118926177/5d44204e-3977-4ed0-a478-9120b9ac971b)

**Additional context**
Add any other context here.

**Comment by rektdeckard** [comment]
While these tools are ubiquitous industry standard, we are scaling back on support for most brand icons. Please see #392 for details.

**Comment by MihirGrand** [comment]
Makes sense. Thanks!
