### ISSUE TITLE
Mouse Icons

### ISSUE THREAD

**Issue by nfoert** [phosphor-icons/homepage#373]
**Describe the requested icon**
Icons showing left click, right click, middle click and possibly scrolling on a mouse (plus one not being clicked or scrolled at all)

**Additional context**
I would use it for directing how user interaction would work on some more complex applications or games. (Ex. Click here to do x, scroll here to zoom, ect.)

**Comment by rektdeckard** [comment]
Added `mouse-left-click`, `mouse-middle-click`, `mouse-right-click`, `mouse-scroll` in v2.1
