### ISSUE TITLE
Coffee bean icon

### ISSUE THREAD

**Issue by zelieponsart** [phosphor-icons/homepage#374]
**Describe the requested icon**
Adding a coffee bean icon would be soooo nice please :)
Our brand is called moka.care, and we would like to symbolize our own "money coin" with a coffee bean ;)
Thank you so much in advance !

**Screenshots**
![CoffeeGrain](https://github.com/phosphor-icons/homepage/assets/143074370/6ccaf870-d323-47a3-85e5-e3c5baec86ba)

**Comment by alexiscolonna** [comment]
Thanks a lot @rektdeckard 🙏
