### ISSUE TITLE
"Office" building icon

### ISSUE THREAD

**Issue by robkovacs** [phosphor-icons/homepage#376]
**Describe the requested icon**
Looking for an icon to represent a company, an office, a workplace... `buildings` seems to be the closest but it doesn't feel like a real "downtown skyscraper", you know?

(I did see #291, but that wasn't very specific.)

![Screenshot 2023-11-15 at 5 02 12 PM](https://github.com/phosphor-icons/homepage/assets/2268116/05c3271d-fa76-4913-ba0d-1bbcbd68867b)

**Screenshots**
It seems like the common thread is including more "windows" to increase the perceived scale of the building.

`Apartment` from Material Symbols:
![Screenshot 2023-11-15 at 4 58 31 PM](https://github.com/phosphor-icons/homepage/assets/2268116/add57835-2505-4d80-a170-552f73013bc9)

`building.2` from SF Symbols:
![Screenshot 2023-11-15 at 4 58 24 PM](https://github.com/phosphor-icons/homepage/assets/2268116/862324f3-2c84-4b0b-9118-d9cb258dd9d3)

A couple options from Streamline... it doesn't necessarily need to be a _pair_ of buildings.
![Screenshot 2023-11-15 at 5 07 18 PM](https://github.com/phosphor-icons/homepage/assets/2268116/53c76b38-cc50-4e90-b6cc-a7df47e62654) ![Screenshot 2023-11-15 at 5 07 23 PM](https://github.com/phosphor-icons/homepage/assets/2268116/e538221e-2766-426a-a775-f6c52cb80e0f)

And the emojis for `office building` and `department store`:
 ![image](https://github.com/phosphor-icons/homepage/assets/2268116/f26b0ce5-e772-4710-9ee9-ad138c489543) ![image](https://github.com/phosphor-icons/homepage/assets/2268116/15cfb14d-1a71-438d-900f-f8ea853ed6d8)

**Additional context**
As indicated by the name of the Material Symbol, this might also be useful to people who want to represent "apartment building" in comparison to "single-family house".

**Comment by rektdeckard** [comment]
Thanks @robkovacs for being thorough and taking the time to look through existing issues! We will do our best to cover a few more building in the next release.
