### ISSUE TITLE
Disney icon

### ISSUE THREAD

**Issue by LokuraPiromana** [phosphor-icons/homepage#383]
Well, I would like to see an Disney (not matter is the castle or the Mickey's ears) icon. I would prefer the oldest castle than the new one. Thank you, 

![image](https://github.com/phosphor-icons/homepage/assets/151430781/55cbb161-4cb8-4abf-b7a5-57e8466b70c4)

**Comment by rektdeckard** [comment]
Out of scope for this project. See #392 (Regarding brand logos).
