### ISSUE TITLE
Icon request: disco

### ISSUE THREAD

**Issue by lsglucas** [phosphor-icons/homepage#387]
**Describe the requested icon**.   
I would like a disco icon.
The core use cases are related to music, parties, bars and nightlife. 

**Screenshots**. 
Some inspiration:

<img width="100" alt="image" src="https://github.com/phosphor-icons/homepage/assets/61513630/7c46d55a-bfa1-4125-87e1-7798955983ee"><br>
<img width="100" alt="image" src="https://github.com/phosphor-icons/homepage/assets/61513630/7f79d478-b03b-480d-89e5-ae893db908c3">
<img width="100" alt="image" src="https://github.com/phosphor-icons/homepage/assets/61513630/e19a7198-c9ed-4f5f-a642-ae3a4e5eb223">

<br>

_Thank you all for the amazing work on ph icons_

**Comment by Cha-Shao** [comment]
maybe you can use `globe`
