### ISSUE TITLE
All thin icons on EGUI are broken

### ISSUE THREAD

**Issue by aspect** [phosphor-icons/homepage#391]
**Describe the bug**
In the EGUI crate of phosphor icons, all thin icon definitions are broken.  The entire icon set looks to be "off by one".  If you have ICON_A, ICON_B and ICON_C, (say LIST_BULLETS and LIST_CHECK), the ICON_C will be on place of ICON_B and ICON_B on place of ICON_A.

**To Reproduce**
Use any icon from `egui_phosphor::thin` module.

**Expected behavior**
Icons should match all the other modules (light etc are ok).  Looks like some processing error that seems to affect only the icons that are inside of the `thin` module

**Comment by rektdeckard** [comment]
I do not maintain the egui crate, I recommend creating an issue over on that repo.
