### ISSUE TITLE
Website / Webpage Icon

### ISSUE THREAD

**Issue by ryanshumway** [phosphor-icons/homepage#395]
**Describe the requested icon**
I'm trying to build out an input field, where a user will submit their URL.. but there isn't an icon to go with this input. I'm using the globe icon but it doesn't really work. 

**Screenshots**
<img width="785" alt="image" src="https://github.com/phosphor-icons/homepage/assets/67422893/0c612f5c-d1f6-498f-b9a8-18ed912cea7e">

**Comment by rektdeckard** [comment]
Does `link` not work for you?

**Comment by ryanshumway** [comment]
Apologies for not getting back to you sooner. Link does the job, I was hoping for more of a "website" icon but link and this globe works. Love the icon pack. It's smashing!

**Comment by rektdeckard** [comment]
`browser`, `browsers`, or `app-window` may also work? Not sure I see us making a `www` icon.

**Comment by ryanshumway** [comment]
Those icons work fine.
