### ISSUE TITLE
icon request: support icon

### ISSUE THREAD

**Issue by karim-skeet** [phosphor-icons/homepage#397]
**Describe the requested icon**
support icons show headphones like those who used a lot in call centers

**Screenshots**

<img width="50" alt="Screenshot 2023-12-29 at 11 31 58" src="https://github.com/phosphor-icons/homepage/assets/150152896/a8c5f997-ea64-48fb-830d-bddc9ff06cf4">

**Comment by rektdeckard** [comment]
We have the `headset` icon.

**Comment by karim-skeet** [comment]
Thank you so much

**Comment by rektdeckard** [comment]
I will add some tags to make it easier to find in search. What did you search for? "headphones"? "support"?

**Comment by karim-skeet** [comment]
i search by support and call center
