### ISSUE TITLE
Icons Request: money icons

### ISSUE THREAD

**Issue by karim-skeet** [phosphor-icons/homepage#398]
**Describe the requested icon**
A lot of icons related with money are missing from phosphor icons, could you please add them, and thank you so much for your efforts.

**Screenshots**
<img width="48" alt="Screenshot 2023-12-29 at 15 27 20" src="https://github.com/phosphor-icons/homepage/assets/150152896/d31250bc-93d4-4a35-861d-fe582a834a45">
<img width="39" alt="Screenshot 2023-12-29 at 15 27 23" src="https://github.com/phosphor-icons/homepage/assets/150152896/2e332fae-5ff9-40c3-bd25-91150ca8a7b1">
<img width="42" alt="Screenshot 2023-12-29 at 15 27 29" src="https://github.com/phosphor-icons/homepage/assets/150152896/19c3133c-b7af-4ce3-9184-c6cb413cf081">

**Additional context**
Add any other context here.

**Comment by rektdeckard** [comment]
Can you be more specific with this request, and include your use-cases that are not covered by existing money icons?

**Comment by karim-skeet** [comment]
Hey, thanks for your response, I need some icons (withdrawal | invoices | transfers_money_icons) throughout my search on the available icons I didn't find any icon that matches my need.

**Comment by rektdeckard** [comment]
Added `hand-withdraw`, `hand-deposit`, `hand-arrow-down`, `hand-arrow-up`, `cash-register`, `invoice`, `money-wavy`, `tip-jar`.
