### ISSUE TITLE
Icon for polls/surveys

### ISSUE THREAD

**Issue by fredericbahr** [phosphor-icons/homepage#405]
**Describe the requested icon(s)**

Hey, thanks for the great library.
I would like to request an icon for polls/surveys.

**References**
Something like this:

1. https://t4.ftcdn.net/jpg/02/48/04/59/360_F_248045991_doOwB0DorOcevRs44cwFvwRHktjVO1Qr.webp
2. https://static-00.iconduck.com/assets.00/poll-icon-511x512-rsm3y3qi.png
3. https://www.svgrepo.com/show/347908/poll.svg

**Additional context**
I need it for my survey app inside a mobile navigation and i think it could be helpful for various other user-centered applications

**Comment by rektdeckard** [comment]
We have `chart-bar` and `chart-bar-horizontal`, these should work as they are very similar to your examples. I'll make sure to improve tagging so they are searchable with poll-related keywords.

**Comment by fredericbahr** [comment]
Hey, thanks for the reply.

Personally i would love the bars in the speech bubble to indicate that this is a survey.

But thanks for two icons and the improved tagging, this would work as well or in the mean time.

**Comment by rektdeckard** [comment]
Added `ranking`.
