### ISSUE TITLE
Icon for Mobile Off or Mobile Unsupported

### ISSUE THREAD

**Issue by gabevandesande** [phosphor-icons/homepage#407]
**Describe the requested icon(s)**

I'd like to see an icon to depict 'Mobile is unsupported' for apps / sites that do not support small screens, or are incompatible on mobile devices. I've attached tabler icon's implementation of both the mobile and tablet versions.

**References**

<img width="198" alt="Screenshot 2024-01-12 at 2 33 55 PM" src="https://github.com/phosphor-icons/homepage/assets/12819055/5c5aa2b9-d221-49e4-afe1-4626744d2b0e">
<img width="210" alt="Screenshot 2024-01-12 at 2 34 25 PM" src="https://github.com/phosphor-icons/homepage/assets/12819055/d0d543b8-43fa-41af-9c3b-598e1233dbf2">

**Additional context**

**Comment by rektdeckard** [comment]
Added `device-mobile-slash`
