### ISSUE TITLE
Podium / standings icon

### ISSUE THREAD

**Issue by srabouin** [phosphor-icons/homepage#421]
**Describe the requested icon(s)**

This icon represents the standings or top rankings of an event. 

**References**

https://fontawesome.com/icons/ranking-star?f=classic&s=solid
https://thenounproject.com/icon/podium-6510734/
https://thenounproject.com/icon/championship-standings-3903131/
https://react-icons.github.io/react-icons/search/#q=podium

**Additional context**

There is a **Trophy** icon but it represents a single winner. There is the **List Numbers** icon that can also be an alternative but it is not explicitly obvious that it is a list of winners.

Thanks for this great library! <3

**Comment by rektdeckard** [comment]
Added `lectern`, `ranking`
