### ISSUE TITLE
Mobile PIN (pincode) icon

### ISSUE THREAD

**Issue by reinos** [phosphor-icons/homepage#424]
**Describe the requested icon(s)**

A PIN icon that represent the pin on a mobile device (when logged in with a pincode instead of a password).

**References**
https://icon-sets.iconify.design/?query=fiber-pin-outline

![Screenshot 2024-02-08 at 11 43 28](https://github.com/phosphor-icons/homepage/assets/633730/f9f7fa21-4e38-475d-94f3-94ce20cb388b)

**Comment by rektdeckard** [comment]
We'll be releasing a `numpad` icon much like [this](https://thenounproject.com/icon/dial-5978428/) in the upcoming update. Is that sufficient?

**Comment by reinos** [comment]
That could be a candidate. For now we created a custom icon with the SVG with a SVG path.

**Comment by rektdeckard** [comment]
Added `numpad`
