### ISSUE TITLE
Menu closed icon

### ISSUE THREAD

**Issue by reinos** [phosphor-icons/homepage#425]
**Describe the requested icon(s)**

It seems that the current set of icons lacks a closing icon for the menu. Basically a hamburger icon with an arrow.

**References**

https://icon-sets.iconify.design/ant-design/menu-fold-outlined/

![Screenshot 2024-02-08 at 12 54 43](https://github.com/phosphor-icons/homepage/assets/633730/391ea95c-c4dd-47c6-a763-5e56203571a3)

**Comment by rektdeckard** [comment]
`text-outdent` seems to be very similar, and shares the same basic geometry of our `list` (hamburger menu) icon. Is this sufficient?
