### ISSUE TITLE
Collection/stack icon

### ISSUE THREAD

**Issue by hadrien-brnd** [phosphor-icons/homepage#427]
Hello Helena and Thobias,

I've been using your icon library to replace Heroicons, and I love it!
I'd love to have a collection/stack icon like this one :
<img width="110" alt="Capture d’écran 2024-02-07 à 16 47 38" src="https://github.com/phosphor-icons/homepage/assets/159528885/ae7f22bc-418f-4eee-b758-d09290bcd484"> <img width="102" alt="Capture d’écran 2024-02-07 à 16 47 25" src="https://github.com/phosphor-icons/homepage/assets/159528885/d389a0ca-9a33-4b43-b18d-ad3f90f66013">

I'm using it to depict Digital Assets/Collection in my app : 
<img width="553" alt="Capture d’écran 2024-02-09 à 10 51 05" src="https://github.com/phosphor-icons/homepage/assets/159528885/9decb14e-5840-49b3-918e-22ffb08843b5">

I know you already have a stack icon. But it doesn't speak the same way as the heroicons one that I'm currently using.
<img width="73" alt="Capture d’écran 2024-02-09 à 10 49 16" src="https://github.com/phosphor-icons/homepage/assets/159528885/79cab8ce-debe-4274-b871-043081dc64e2">

Kind regards,
Hadrien.

**Comment by rektdeckard** [comment]
Added `cards-three`

**Comment by hadrien-brnd** [comment]
Thanks a lot 🔥
