### ISSUE TITLE
Unarchive icon

### ISSUE THREAD

**Issue by mcintyret** [phosphor-icons/homepage#433]
**Describe the requested icon(s)**

An "Unarchive" icon - to symbolise the inverse action of the "ArchiveBox" icon. Could be exactly the same as "ArchiveBox" with the arrow pointing up instead of down! Maybe the same for "ArchiveTray" too.

**References**

**Additional context**

**Comment by rektdeckard** [comment]
Added as `tray-arrow-up` and `box-arrow-up`, corresponding with the renaming of the icons you mentioned.
