### ISSUE TITLE
Binary Icon

### ISSUE THREAD

**Issue by fredericbahr** [phosphor-icons/homepage#434]
**Describe the requested icon(s)**
I would love to have an icon displaying binary code

**References**
1. [Binary horizontal](https://www.google.com/search?sca_esv=ee8cc78a83643a01&rlz=1C1GCEA_enDE1095DE1095&q=binary+icon&uds=AMwkrPvFwQQy0EH0_6ou8JUrWCkDCDbUjSPck3uO1LYUZ5DpBoL2_BckZ55FEt36gbgVbgqZmg-Fw0_mafWl_VwyI54C0dPW23dWT3VGgCGwYANkbQtcyMT0tcI1AqoukyBL8OZLwbkh&udm=2&sa=X&ved=2ahUKEwiUitOexMOEAxWv7gIHHX3JAGQQtKgLegQIDRAB&biw=1920&bih=1031&dpr=1#vhid=ga1IPEspLe6uVM&vssid=mosaic)
2. [Binary Square](https://www.google.com/search?sca_esv=ee8cc78a83643a01&rlz=1C1GCEA_enDE1095DE1095&q=binary+icon&uds=AMwkrPvFwQQy0EH0_6ou8JUrWCkDCDbUjSPck3uO1LYUZ5DpBoL2_BckZ55FEt36gbgVbgqZmg-Fw0_mafWl_VwyI54C0dPW23dWT3VGgCGwYANkbQtcyMT0tcI1AqoukyBL8OZLwbkh&udm=2&sa=X&ved=2ahUKEwiUitOexMOEAxWv7gIHHX3JAGQQtKgLegQIDRAB&biw=1920&bih=1031&dpr=1#imgrc=xzgA9W-g135-EM&imgdii=MVJWwLwyXeqHSM)

**Additional context**

This could be used in various coding projects. I would like to display it in a footer showing that the site was self-built with zeros and ones

**Comment by rektdeckard** [comment]
Nice idea. Have added to backlog 👍

**Comment by rektdeckard** [comment]
Added `binary`
