### ISSUE TITLE
Flip icon

### ISSUE THREAD

**Issue by arscodicis** [phosphor-icons/homepage#438]
**Describe the requested icon(s)** I’d like an icon that has a vertical rectangle with a curved arrow around it. 

**References** It could be used to symbolize “flipping” or “rotating” a view or part of an app/website. An example might be indicating the flipping of a flashcard.

See: https://thenounproject.com/icon/flip-over-267318/

**Additional context** None further.

**Comment by rektdeckard** [comment]
We have plenty of arrows that could indicate this. Does `arrow-arc-right`, `arrow-clockwise`, `arrows-clockwise` not work for your use-case?

**Comment by arscodicis** [comment]
I'll make those icons work, but if you find time to add an icon like I mentioned that'd be great. I understand that you can't go through the process of adding every icon any random person asks for, though. :)

**Comment by rektdeckard** [comment]
We'll be adding a `device-rotate` icon in the upcoming release, something like this: https://thenounproject.com/icon/rotate-6198262/

**Comment by arscodicis** [comment]
Yes, that works. Thanks!
