### ISSUE TITLE
Lotion bottle

### ISSUE THREAD

**Issue by mmed199** [phosphor-icons/homepage#439]
**Describe the requested icon(s)**

🧴 A bottle of lotion for the skin, such as moisturizer or sunscreen (sunblock). May be used for other hygienic liquids, including shampoo and body wash), as well as beauty products.

**References**

https://emojipedia.org/lotion-bottle
https://www.shutterstock.com/fr/image-vector/body-lotion-icon-outline-glyph-style-2311155853

**Additional context**
May be used for every cosmetic product

**Comment by rektdeckard** [comment]
`hand-soap` should work for this purpose, no? I'll add some tags to make it easier to search.

**Comment by mmed199** [comment]
@rektdeckard Yes it does the job. Thanks, I'll close the issue
