### ISSUE TITLE
The Apple logo is cut out at the bottom.

### ISSUE THREAD

**Issue by nephlin7** [phosphor-icons/homepage#440]
**Describe the bug**

The Apple logo is cut out at the bottom. Check the images for references:

**Expected behavior**
-

**Screenshots**
Original logo
 
![image](https://github.com/phosphor-icons/homepage/assets/22168189/80803000-ccdc-4ca7-a658-e6ee26279524)

Logo in the library

![Screenshot 2024-03-04 at 07 40 07](https://github.com/phosphor-icons/homepage/assets/22168189/a7b9730c-58bc-4b4a-9e34-ba50095420df)

**Context (please complete the following information):**
Detected on @phosphor-icons/react, but seems to be a general issue of the SVG

**Additional notes**

**Comment by rektdeckard** [comment]
The icon is designed intentionally (see #392). If you are looking for official brand assets (which we recommend), please get them from Apple.
