### ISSUE TITLE
hypodermic needle

### ISSUE THREAD

**Issue by codysue** [phosphor-icons/homepage#442]
**Describe the requested icon(s)**

I work for a healthcare company that utilizes the Phosphor library for our system iconography. We have a need for a hypodermic needle or syringe to indicate vaccine resource centers. 

**References**

I tried adding screenshots here but would not allow for whatever reason. The text goes "Protect your health and your community. Learn about your vaccine and testing coverage" and has a Hypodermic Needle next to the title of "Vaccine Resource Center" 

**Additional context**

**Comment by rektdeckard** [comment]
We have the `syringe` icon, which is also tagged as "needle" in the database. Please check existing icons before making a request, thanks!
