### ISSUE TITLE
Stack add

### ISSUE THREAD

**Issue by kulbir5** [phosphor-icons/homepage#447]
You already have [Stack Icon](https://phosphoricons.com/?q=%22stack%22&color=%227c003f%22&weight=%22light%22&size=68)
![CleanShot 2024-03-18 at 09 47 05@2x](https://github.com/phosphor-icons/homepage/assets/43150280/8de35ec2-e3d9-4575-9b59-5f5bc4c789a0)

**Requesting "Stack +" Icon** 

![CleanShot 2024-03-18 at 09 45 09@2x](https://github.com/phosphor-icons/homepage/assets/43150280/399dc452-e9b3-40b6-9b91-694935a95ad2)

**Comment by rektdeckard** [comment]
Closing as duplicate of #225

**Comment by rektdeckard** [comment]
Added `stack-plus`, `stack-minus`
