### ISSUE TITLE
Error when evaluating SSR module in remix-create@latest

### ISSUE THREAD

**Issue by nikolailehbrink** [phosphor-icons/homepage#459]
**Describe the bug**

Wanted to integrate the icons in a remix project with their latest `vite` setup. After importing icons from the ssr package, `vite` has an `Error when evaluating SSR module /app/routes/_index.tsx: failed to import "@phosphor-icons/react/dist/ssr"`.  After importing it with the standard package, there is an `Internal server error: Cannot find package`

**Steps to Reproduce**

Create a new project with `pnpm dlx create-remix@latest` or `npx create-remix@latest` and try to import an icon with either the normal react or the ssr package.

**Expected behavior**
I am able to import the icons.

**Context (please complete the following information):**

**Comment by rektdeckard** [comment]
Looking into it. In future please leave issues related to the React library over at https://github.com/phosphor-icons/react.

**Comment by rektdeckard** [comment]
Confirmed locally, this stems from the same root cause as https://github.com/phosphor-icons/react/issues/90. Fix incoming.

**Comment by nikolailehbrink** [comment]
> Looking into it. In future please leave issues related to the React library over at https://github.com/phosphor-icons/react.

Will do, sorry for the inconvenience!

**Comment by nikolailehbrink** [comment]
> Confirmed locally, this stems from the same root cause as [phosphor-icons/react#90](https://github.com/phosphor-icons/react/issues/90). Fix incoming.

Okay, just saw that you release a fix, I will try it out tomorrow and test it! Thanks!
