### ISSUE TITLE
navigation-arrow to the right

### ISSUE THREAD

**Issue by vanlooverenkoen** [phosphor-icons/homepage#469]
**Describe the requested icon(s)**

I would like to have switched version of `navigation-arrow`

**Comment by rektdeckard** [comment]
What do you mean by "switched"?

**Comment by vanlooverenkoen** [comment]
Yes indeed

**Comment by rektdeckard** [comment]
We typically leave that kind of thing up to the user. Any design software or platform can do this without needing to bloat out library.

**Comment by vanlooverenkoen** [comment]
Alright makes sense! Good to know.

**Comment by vanlooverenkoen** [comment]
The reason why I'm asking this is because all other icons I find that represent navigation point to the right.
