### ISSUE TITLE
Jest testID react-native

### ISSUE THREAD

**Issue by rodrigodiasf1984** [phosphor-icons/homepage#480]
Hi guys, can you please add the testID to the icons?  Thanks 

![image](https://github.com/phosphor-icons/homepage/assets/30758309/bc968c78-838f-42f4-b9df-241598cbf9b5)

**Comment by rektdeckard** [comment]
We do not maintain the React Native library, please create an issue over on the [phosphor-react-native](https://github.com/duongdev/phosphor-react-native) repo.
