### ISSUE TITLE
Version 2.1 on Flutter ?

### ISSUE THREAD

**Issue by CharlotteJu** [phosphor-icons/homepage#484]
**Describe the bug**
Can't upgrade to 2.1 version

**Screenshots**
![Capture d’écran 2024-04-22 à 11 24 32](https://github.com/phosphor-icons/homepage/assets/54888583/fff49f7d-722d-4d32-8e8f-44ace60bd7fe)

**Context (please complete the following information):**

**Comment by jslattery26** [comment]
Wrong repository -  you want this: https://github.com/phosphor-icons

And they are still a version behind. `2.0.1`

**Comment by rektdeckard** [comment]
It's now up to date 👍
