### ISSUE TITLE
Clear text formatting icon

### ISSUE THREAD

**Issue by akkie** [phosphor-icons/homepage#485]
**Describe the requested icon(s)**

For rich text editors it's common to clear the formatting of a text. Actually there is an eraser icon, which I think is to generic. For clearing text I think something like the following icon is more appropriate.

**References**
<img width="181" alt="image" src="https://github.com/phosphor-icons/homepage/assets/307006/3f2e8002-c818-4132-8066-45a52b28e8d3">

**Comment by rektdeckard** [comment]
We have `text-t-slash`, which is an established symbol for clearing formatting.
