### ISSUE TITLE
Calculation Icons

### ISSUE THREAD

**Issue by alirezas** [phosphor-icons/homepage#487]
**Describe the requested icon(s)**
Calculation icons with four basic mathematical operations variants

**References**
![accounting](https://github.com/phosphor-icons/homepage/assets/811564/94b9c138-cb6c-40df-bdf0-8daf9351aee6)
![calculator](https://github.com/phosphor-icons/homepage/assets/811564/2725724f-f785-45a0-b0e5-080689e43d40)
![keys](https://github.com/phosphor-icons/homepage/assets/811564/355cb571-a5c6-4022-94b1-1aaba5891866)

**Additional context**

**Comment by rektdeckard** [comment]
`math-operations`
