### ISSUE TITLE
Missing icon on Framer

### ISSUE THREAD

**Issue by KerryVN** [phosphor-icons/homepage#496]
Hi, I can't find the ranking icon in Framer.

**Comment by rektdeckard** [comment]
Hi @KerryVN, this is a Framer thing! It looks like there may [already be a report](https://www.framer.community/c/requests/phosphor-icons-v2-1), in case you want to +1 it.

**Comment by KerryVN** [comment]
Thank you! New to Framer so not sure where to report these things yet. Appreciate your help 😁
