### ISSUE TITLE
Browser icons & more

### ISSUE THREAD

**Issue by Kopyov** [phosphor-icons/homepage#50]
Again, thank you so much for such an awesome icon set!

A few suggestions for the next release:

1. Browser icons: Firefox, IE, Edge, Opera, Chrome and Safari
2. Square half - the same, but in horizontal direction. Something like .ph-square-half-horizontal
3. More file types - currently you have added only PDF, but would be extremely useful to have more file types: ZIP, PNG, JPG, XLS, CSV, DOC, PPT.
4. ZIP icon - apart from file type, which says "ZIP", having a separate icon for zip archive would be super handy
5. Some other logos related to development - SASS, CSS, HTML, JS, Angular, React, Vue, Tailwind

Cheers!

**Comment by rektdeckard** [comment]
Taking a look at some of these for the next release!

**Comment by rektdeckard** [comment]
Added `google-chrome-logo` in v1.4.0. More browsers to come later!
Also added `square-half-bottom`, and a WHOLE mess of file type icons.

**Comment by Kopyov** [comment]
you are my hero. Thanks for keeping this awesome library alive!

**Comment by RenoLooijmans** [comment]
Any change the other browser icons are still in the pipeline?

**Comment by rektdeckard** [comment]
@RenoLooijmans unlikely we will add browser icons, see #392
