### ISSUE TITLE
Support for Storybook on React Native

### ISSUE THREAD

**Issue by rodrix** [phosphor-icons/homepage#503]
Hi guys, are someone using this amazing lib on expo's based react-native apps with storybook documentation lib enabled?

The `phosphor-icons` itself works very well through `phosphor-react-native` lib on app's execution environment, but not on storybook:web runtime.

When I try to see some component using phosphor icon, the storybook fail with this message:

![image](https://github.com/phosphor-icons/homepage/assets/1629822/03dc9fbd-0b45-4a23-be19-bcf990a8da76)

Someone already did this setup?

**Comment by rektdeckard** [comment]
We don't maintain the `phosphor-react-native` port, please create an issue on [that repo](https://github.com/duongdev/phosphor-react-native).
