### ISSUE TITLE
Charity icon

### ISSUE THREAD

**Issue by vanlooverenkoen** [phosphor-icons/homepage#532]
**Describe the requested icon(s)**

**References**

![image](https://github.com/user-attachments/assets/16e414c4-8033-48dc-bac5-17f1b966d71f)

**Additional context**

**Comment by rektdeckard** [comment]
`hand-heart`

**Comment by vanlooverenkoen** [comment]
Can we add the Charity tag to that icon? So it is easier to find?

**Comment by rektdeckard** [comment]
Sure thing
