### ISSUE TITLE
Add a circle slash icon

### ISSUE THREAD

**Issue by gcristianber** [phosphor-icons/homepage#541]
**Describe the requested icon(s)**

Circle Slash Icon - This icon symbolizes as a BLOCK or PROHIBITED to a certain thing.

**References**

![image](https://github.com/user-attachments/assets/46c65a20-fe70-4b6d-83e6-b87342438dfa)

**Additional context**

**Comment by rektdeckard** [comment]
We have the `prohibit` and `prohibit-inset` icons already.
