### ISSUE TITLE
Icons have different names on the Figma plugin compared to web 

### ISSUE THREAD

**Issue by Bosch-0** [phosphor-icons/homepage#560]
**Describe the bug**

Example, using the Figma plugin the imported icon is called AddressBook. On the website it's address-book. It would be helpful if these matched.

**Comment by rektdeckard** [comment]
With naming conventions being different across many of the languages and frameworks we support, we will never be able to give icons the same name format everywhere. We feel it's better to have the Figma library share the same PascalCase naming as React, and the website makes sense to match both the SVG assets and CSS classes.
