### ISSUE TITLE
Bluesky Logo (Social Network)

### ISSUE THREAD

**Issue by tiagohenriqueferreira** [phosphor-icons/homepage#579]
**Describe the requested icon(s)**

Bluesky  Logo (butterfly)  

**References**

https://bsky.app/
![Bluesky_Logo svg](https://github.com/user-attachments/assets/1f29d75b-f772-420f-b6a2-8ce41b950e9b)

**Additional context**

For use in share buttons or social media items

**Comment by rektdeckard** [comment]
Closing as duplicate of #446. Give a 👍 over there to show your support!
