### ISSUE TITLE
Add a way to copy the icon to the Clipboard similar to the Windows Character Map application for use in software such as CorelDraw

### ISSUE THREAD

**Issue by insinfo** [phosphor-icons/homepage#593]
Add a way to copy the icon to the Clipboard similar to the Windows Character Map application for use in software such as CorelDraw

![image](https://github.com/user-attachments/assets/e0514293-bdf7-408a-a9ee-5e97aca93989)
![image](https://github.com/user-attachments/assets/657bc437-8239-4844-b0cc-55a55ef01389)

**Comment by rektdeckard** [comment]
That's what this button does!![Screenshot_20240927-100923_Firefox (1).jpg](https://github.com/user-attachments/assets/17035422-348e-4a47-af88-d78bbb819276)

**Comment by insinfo** [comment]
I'm sorry, I hadn't really seen this tab, but I just tested it and it doesn't seem to be working correctly. I copied the "ph-align-center-horizontal" icon and pasted it into CorelDraw and a heart icon appeared for me. I downloaded the phosphor Regular font as you can see in the print.

![image](https://github.com/user-attachments/assets/fab408e7-f617-4a4d-a043-2db3b449bd63)

![image](https://github.com/user-attachments/assets/dadee362-07c6-4164-a852-1435322a55be)

**Comment by rektdeckard** [comment]
The "Copy Unicode" feature only stabilized in version `2.1.0` of the font and later. You'll need to use a recent version of the font for the copy feature to work. It will be stable from now on.
