### ISSUE TITLE
Its me icon

### ISSUE THREAD

**Issue by vanlooverenkoen** [phosphor-icons/homepage#607]
**Describe the requested icon(s)**

This is an icon for a social login button. (Its me is a company that allows you to log in into government applications in Europe)

**References**

https://michel.belgium.be/sites/default/files/styles/ece_max/public/ece_images/1200px-Itsme%C2%AE_logo_0.jpg?itok=HljA0qwB

**Additional context**

**Comment by rektdeckard** [comment]
I don't think this meets our criteria for brand logos, being primarily for Belgian audience only. Brands in general are something we're trying to move away from, and this is simply too specific for Phosphor. I'd recommend using their official first-part brand logo. 

Please see https://github.com/orgs/phosphor-icons/discussions/392 for more details on the brand policy.

**Comment by vanlooverenkoen** [comment]
Alright no problem, I do have another question. I will create my own package for my own branded app icons. I had another question. Can I create a library that includes phosphor icons? 

For example I use 5 phosphor icons. Can I use in a single package for my brand? And publish it to pub.dev?

Ofcourse I will do the following:

list all phosphor icons in the readme.md with a link to the phosphor icons. Add credits to the phosphor library?

**Comment by rektdeckard** [comment]
Yes, Phosphor is MIT-licensed. You can extend the library for your own purposes as long as you include our license file, or link to it.

**Comment by vanlooverenkoen** [comment]
Alright cool! I will link back to this ticket if I have created my own icon library for my brand :) thanks a lot! phosphor icons is still my go to library. And will be used by my brand library! Thanks a lot!
