### ISSUE TITLE
Icon request: under construction / work in progress

### ISSUE THREAD

**Issue by rienheuver** [phosphor-icons/homepage#609]
**Describe the requested icon(s)**

Icons to be used for 'under construction' and 'work in progress'.

Specific use case: we're working on an app which wants to show buttons to some upcoming features. We currently use the hammer icon for it, see this screenshot. But it's not ideal for it.
![image](https://github.com/user-attachments/assets/b8499c7c-7d7a-458d-9b9c-250f8a87611f)

**References**
I was thinking something along these lines. These are just screenshots from google images

![image](https://github.com/user-attachments/assets/46b913b4-271f-4ca4-a397-57c3f3e6de2b)
![image](https://github.com/user-attachments/assets/bb73d338-4b43-4afc-a7db-d4887d4cfe09)
![image](https://github.com/user-attachments/assets/70932d4c-29e3-42c7-9b6c-fe8bfd3d6fcc)

**Comment by rektdeckard** [comment]
`traffic-cone`,  `barricade`, `hard-hat` don't work for you?

**Comment by rienheuver** [comment]
Must say I hadn't found traffic-cone and quite like that! The others are not clear enough for their purpose I think

**Comment by minoraxis** [comment]
Closing this one since you found `traffic-cone`. We can add a few tags to it so it's easier to find.
