### ISSUE TITLE
Top Right Dot Notification

### ISSUE THREAD

**Issue by sreynoso** [phosphor-icons/homepage#613]
**Describe the requested icon(s)**

I'd like a dot in top right corner to use like a notification over another icon, eg: bell or menu

**References**

![image](https://github.com/user-attachments/assets/1f9ea5cd-4882-497c-9a20-9debe2f3c773)
![image](https://github.com/user-attachments/assets/be6739fc-b6cf-428e-93e2-d57a95f9b14f)

**Additional context**

**Comment by rektdeckard** [comment]
This seems more like a UI element you should implement you should implement in your application, not an icon.
