### ISSUE TITLE
Dashboard Icon

### ISSUE THREAD

**Issue by howdyjules** [phosphor-icons/homepage#634]
**Describe the requested icon(s)**

I’m reaching out to see if you could create a dashboard icon. It Could be used for an app next to a navigation item called "Dashboard". 

**Additional context**

Maybe four different sized rectangles representing a dashboard grid?

**Comment by Jamiul-Bari** [comment]
how about 'squares-four'

**Comment by rektdeckard** [comment]
Duplicate of #617
