### ISSUE TITLE
Logout-cirl

### ISSUE THREAD

**Issue by shivamrvgupta** [phosphor-icons/homepage#646]
**Describe the requested icon(s)**

**References**
![solar--logout-broken](https://github.com/user-attachments/assets/f8efd2e7-60b3-4a0d-85a8-7de1df3aeb4d)
![solar--logout-broken](https://github.com/user-attachments/assets/e136bdb2-581d-4600-a4fc-c91ee4874ab5)

**Additional context**

**Comment by fredericbahr** [comment]
Sign-Out might be sufficient?
https://phosphoricons.com/?q=%22sign-out%22
