### ISSUE TITLE
Homepage search results aren't appropriately marked as buttons

### ISSUE THREAD

**Issue by bkjohnson** [phosphor-icons/homepage#651]
**Describe the bug**

This might not be a bug, but from an accessibility perspective some of the markup on the homepage is not what I would expect. I tried to use a keyboard-based workflow to perform some actions on the page, and this requires the markup to conform to certain standards. While doing this I was surprised to see that the search result icon "buttons" weren't actually buttons, and weren't getting recognized as interactive as a result.

**Steps to Reproduce**

1. Search for an icon, i.e. [smile](https://phosphoricons.com/?q=%22smile%22)
2. Hover over the search results and notice the cursor and the background change to suggest interactivity
3. Use the `Tab` key to tab between the results in an interactive way
4. Click on a result and notice that it triggers the "detail preview" aside to be revealed (like a button action)
5. Use a browser extension like vimium (or look at the accessibility tree) to reveal interactive elements and notice that the search results aren't considered interactive.

**Expected behavior**

The search results are `<button>`s instead of `<div>`s, or they have `role="button"`.

**Screenshots**

This shows the search results view with the `f` key pressed to highlight interactive elements (buttons and links) and giving each one a keyboard shortcut.

![image](https://github.com/user-attachments/assets/f91735db-5bf9-4b3e-a82d-daea9c7aca42)

When I modify the markup using the devtools inspector, notice how the "button" is appropriately recognized by the extension as well as the accessibility tree:

![image](https://github.com/user-attachments/assets/ec014568-44bb-4dd5-9a67-0be5aeb3f5d1)

![image](https://github.com/user-attachments/assets/d498691a-9a5d-416f-99e2-4b1243abf16e)

**Context (please complete the following information):**

- OS: Ubuntu 22.04
- Browser/Environment: Firefox
- Library: N/A
- Version: N/A

**Additional notes**

If you accept contributions, I'm willing to try to open a PR to address this.

**Comment by rektdeckard** [comment]
Thanks for pointing that out! We'd be happy for your contribution if you feel like fixing it. If not, I'll get to it in the next day or so!

**Comment by bkjohnson** [comment]
That was fast, thank you!
