### ISSUE TITLE
Svelte library

### ISSUE THREAD

**Issue by akiarostami** [phosphor-icons/homepage#79]
First of all, this is an amazing library. Thank you!

You seem to have support for many platforms, but not Svelte. There is an unofficial library for Svelte support, but it doesn't get updated often. I was wondering if you'd consider adding Svelte to your officially supported platforms?

Thank you.

**Comment by akiarostami** [comment]
Yes, @haruaki07 updated his library immediately after I left a comment. It would be really great to add the svelte code to your wonderful library. I hope @haruaki07 accepts this!

**Comment by joebudi** [comment]
Any updates on svelte support? Considering using phosphor for a large OSS project that users svelte.

**Comment by rektdeckard** [comment]
The community port mentioned above, [phosphor-svelte](https://github.com/haruaki07/phosphor-svelte), is well-maintained. They haven't had any updates in a while because we haven't either! We recommend using it.

I don't see myself making an official Svelte lib, as someone who hasn't and doesn't use the framework, but as I said above, we'd be happy to consider any community initiative to bring one under our roof.

**Comment by rektdeckard** [comment]
Marking as closed, since the lib exists and I have no plans to duplicate the effort!

**Comment by babakfp** [comment]
@rektdeckard

> I don't see myself making an official Svelte lib, as someone who hasn't and doesn't use the framework, but as I said above, we'd be happy to consider any community initiative to bring one under our roof.

Hi

I made this library [phosphor-icons-svelte](https://www.npmjs.com/package/phosphor-icons-svelte).

I've been using Svelte myself for a few years now, and the first time I used Phosphor Icons was for this project [Angle Berry](https://angle-berry.vercel.app/login?username=demo&password=demodemo).

I'd be open to moving this library under phosphor-icons and I'd be happy to maintain it.

[The reasons why I made this library](https://www.npmjs.com/package/phosphor-icons-svelte#why-did-i-build-this).

**Comment by xshapira** [comment]
@rektdeckard Please consider @babakfp suggestion.

Thank you so much for both of you. The community truly appreciates your hard work 👍
