### ISSUE TITLE
Icons look too thin at 16px

### ISSUE THREAD

**Issue by feute** [phosphor-icons/homepage#85]
**Describe the bug**
Hello. I found out about this icon set through Framer. I currently use [Radix Icons](https://icons.modulz.app/), but I liked Phosphor more because of the extensive number of icons and the weights/variants, so I decided to use it for my project. At first glance, from the Phosphor website, they look pretty good, but there's a big difference from 20px to 16px (this is with the regular weight). The 16px ones look very thin in comparison, also there's a big jump from regular to bold at 16px. In my opinion, some of the 16px regular icons should be used as the thin/light variant.

**To Reproduce**
1. Go to phosphoricons.com
2. Change the icons size to 16px
3. Compare the icons from 16px to 20px, and from 16px regular to 16px bold.

**Expected behavior**
The icons should look a bit bolder/sharper.

**Screenshots**
I made some comparisons between Phosphor Icons and Radix Icons:

![Screenshot 2021-12-09 at 17-11-33 CodeSandbox](https://user-images.githubusercontent.com/15493430/145478779-5a80cb94-c00c-49d8-9748-38dda803208e.png)

The Phosphor ones don't look as sharp. They look better when zooming in a little, but not at the default 16px size.

Here's a comparison between the 16px regular and 16px bold icons:

![Screenshot 2021-12-09 at 17-17-12 CodeSandbox](https://user-images.githubusercontent.com/15493430/145479229-2a2cb341-b2d5-4eb4-8449-b12ccc31f1b3.png)

And here's the first comparison (between Phosphor and Radix) in a black background with white text:

![Screenshot 2021-12-09 at 17-18-54 CodeSandbox](https://user-images.githubusercontent.com/15493430/145479467-0d3335a4-3eb1-4982-8972-f207e6bc675e.png)

Here's where it's evident that they don't look as clear/sharp as it should be. I would expect that behaviour from a thinner weight, but not on regular; and the bold weight looks *too* bold.

Here's a codesandbox where you can see the comparison:
[https://codesandbox.io/s/phosphor-radix-icons-9mg6y?file=/src/App.js](https://codesandbox.io/s/phosphor-radix-icons-9mg6y?file=/src/App.js)

**Desktop (please complete the following information):**
 - OS: Fedora Linux 35 Workstation Edition
 - Browser Firefox
 - Version 94.0

**Additional context**
I use the React package for Phosphor Icons. I assume there's no difference since the icons shown on Phosphor look the same.

**Comment by minoraxis** [comment]
Hi @feute, thanks for your detailed post. From your screenshots, Phosphor looks fuzzy and harder to read white on black — not ideal! We want to focus on some polish work next release, and can do some testing around sharpness. Our Thin, Light, and Bold weights particularly need more love.

To give you some context, we snap to to the pixel sometimes, but often fold to .5px at the 16px size. This gives us more fidelity to work with given our "one size fits all" approach (one glyph is used for any size application) and enables Phosphor's style. In icon sets that custom-cut _every_ size, you can achieve more sharpness, but it's also much more complex and heavy to create, maintain, and use. Of course, the tradeoff is what you're seeing — though snapping to .5px renders fine on many modern screens, it doesn't for all. :/

A note on canvas size: an odd-numbered canvas like Radix's 15px size allows for pixel-snapping of centered 1px strokes like the arrow stem, while canvases like 16px and 24px prioritize usage in our latest 8-pt grid systems. 24 seems to be the most popular today. It depends on what's important for the use case.

Hope this answers your issue for now. We'll take a deeper look at how to improve the crispness.

**Comment by rektdeckard** [comment]
We've greatly improved pixel-fitting of the majority of the icon set with v2.0.0, so you should definitely see better sharpness in most use-cases! As @minoraxis says, though, this is a variable-size icon set and there is no magic bullet solution for this. Based on our icon style and our priorities in terms of flexibility and ease-of-use, we've probably done the best we can and anything else would be out of the scope of the project.

That said, I would *highly recommend* using the [@phosphor-icons/web](https://github.com/phosphor-icons/web) implementation, or the underlying icon fonts, if you are looking for better sharpness and rendering. Fonts simply do better than SVG in this regard, on most platforms and OSes, and anecdotally, the difference is pretty clear.

Thanks for pointing this out, hope we've made some improvement this round. Marking as closed!
