### ISSUE TITLE
Shapes Icon

### ISSUE THREAD

**Issue by nc** [phosphor-icons/homepage#86]
Describe the requested icon
Icon to represent the concept of a shape

Screenshots
Like `circles-four` but with a circle, rectange, triangle and a hexagon? Or three shapes circle, rectangle and triangle. 
The notion 'templates' icon is a great example of this.

Additional context
For use in a whiteboard app where you can pick adding a shape before choosing which type of shape.

**Comment by nc** [comment]
e.g. https://thenounproject.com/icon/shapes-256628/
e.g. https://thenounproject.com/icon/shape-3106475/
e.g. https://thenounproject.com/icon/shape-4472395/

**Comment by RichardBarrett** [comment]
+1 except I would like it to be something to represent a collection of components/elements

<img width="202" alt="image" src="https://user-images.githubusercontent.com/1667234/161525428-96836706-5b3c-41d4-834f-e6af13d0df37.png">

**Comment by rektdeckard** [comment]
Added `shapes` in v2.0.0
