### ISSUE TITLE
Vinyl Record Icon

### ISSUE THREAD

**Issue by ohitsdylan** [phosphor-icons/homepage#87]
**Describe the requested icon**
There are a lot of cool music & audio related icons, but no vinyl record icon! We need some retro love.

**Screenshots**
I drew up an icon that I think works well with the style.
![vinyl](https://user-images.githubusercontent.com/55002846/147286581-e390ded2-4a34-41fa-9b53-1fe292562804.png)

**Comment by rektdeckard** [comment]
Added `vinyl-record` in v2.0.0
