### ISSUE TITLE
Gluten-free icon

### ISSUE THREAD

**Issue by DaveKeehl** [phosphor-icons/homepage#90]
**Describe the requested icon**
First of all, I want to say that I love your icons and they are my go-to when I need to use any :D
That being said, I'm currently building the UI for a food-related e-commerce website and couldn't find an icon suited to represent a gluten-free product.

**Screenshots**
![360_F_330561589_04nKZPPpT7h67oMUheYrOWvnKNZd6fuw](https://user-images.githubusercontent.com/34663397/147374362-d6e7885f-6dcb-42d6-83f7-5729392fe6e1.jpeg)
![5591278](https://user-images.githubusercontent.com/34663397/147374364-fa8b3cbc-c9d6-4c0a-8db1-70f3fa826429.png)
![png-transparent-gluten-free-logo-mobile-phones-no-symbol-computer-icons-telephone-call-gluten-free-icon-telephone-call-logo-sign](https://user-images.githubusercontent.com/34663397/147374365-b598b29d-1c6a-4612-9bf5-009cf25de7dc.png)

**Comment by rektdeckard** [comment]
Added `grains`, `grains-slash` in v2.0.0
