### ISSUE TITLE
Revised Cursor Icon

### ISSUE THREAD

**Issue by nc** [phosphor-icons/homepage#93]
**Describe the requested icon**
Icon for a cursor, closer to a standard OSX cursor that can be recoloured for each user. 
The current cursor has too thin of a 'stalk' making it look weird in place.

**Screenshots**
Something closer to https://thenounproject.com/icon/cursor-1089794/ which has a thicker stalk, and an appearance closer to the standard OSX cursor. 

**Additional context**
For use in a multiplayer whiteboarding app

**Comment by minoraxis** [comment]
Good suggestion. Accepting it for next release.

**Comment by rektdeckard** [comment]
Revised the `cursor` per your suggestion, and added `cursor-click` for good measure, in v2.0.0!
