### ISSUE TITLE
DEV Community icon

### ISSUE THREAD

**Issue by allytiago** [phosphor-icons/homepage#97]
**Describe the requested icon**
A constructive and inclusive social network for software developers.

**Screenshots**
![Icon-App-83.5x83.5@2x.png](https://user-images.githubusercontent.com/47113005/148813512-33a3c9b6-d357-46e2-b961-82ef83068c3b.png)

![Screenshot_20220110-144447_Samsung Internet.jpg](https://user-images.githubusercontent.com/47113005/148813490-d046ade7-8d83-4c5c-81f2-cbf035238fe6.jpg)

![Screenshot_20220110-144629_Samsung Internet.jpg](https://user-images.githubusercontent.com/47113005/148814053-de8de8af-ba75-4191-9608-6ed4907511aa.jpg)

**Additional context**
social network brand: https://dev.to/brand

**Comment by rektdeckard** [comment]
Added `dev-to-logo` in v2.0.0
