### ISSUE TITLE
Icon Request for Read.cv

### ISSUE THREAD

**Issue by pscldesign** [phosphor-icons/homepage#98]
**Describe the requested icon**
Read.cv is getting more and more popular, would be great to add to the social icons!

**Screenshots**
If applicable, add screenshots to help illustrate the icon appearance.

**Additional context**
Here's a link to the site: [https://read.cv/](https://read.cv/)

**Comment by rektdeckard** [comment]
Added `read-cv-logo` in v2.0.0
