### ISSUE TITLE
Icon Request: VR

### ISSUE THREAD

**Issue by ashconnell** [phosphor-icons/homepage#99]
**Describe the requested icon**
VR

**Screenshots**
![image](https://user-images.githubusercontent.com/760516/151275899-1cbffd35-42f0-4445-a134-307fdb1c291c.png)
![image](https://user-images.githubusercontent.com/760516/151275916-90b03cc9-7203-47ee-b1d3-9d74b5b68f16.png)
![image](https://user-images.githubusercontent.com/760516/151275956-c899a41d-ddac-4bd6-b363-f65544b02827.png)

**Comment by rektdeckard** [comment]
Added `virtual-reality`, `google-cardboard-logo` in v2.0.0
